### ISSUE TITLE
Adding Unit tests in the whole project

### ISSUE THREAD

**Issue by juan-medina** [ev3dev-lang-java/ev3dev-lang-java#209]
```gherkin
Feature: Develop the library EV3Dev-lang-java
In the third generation of Lego Mindstorms, 
it is possible to install a complete Linux distribution and a complete Oracle JRE. 
It is necessary to develop a library to use the hardware compatible with EV3Dev.

    Scenario: Testing features
        Given The library EV3Dev-lang-java
        Then It is necessary to have the possibility to test the library without any physical device.
        And Reduce the time to release
        And Increase the Maintainability
```

**Related issue:**
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/245

**Note:** To close this issue, it is necessary to reach 75% of Coverage

**Comment by jabrena** [comment]
yes, it is something pending. I will add them.

**Comment by jabrena** [comment]
It is necessary to research how to add juice in the same way that it is done on xbot and stronghold.
https://github.com/Team488/Shared/blob/master/2015%20Competition%20Season/CompetitionBot/workspace/XbotCommonLib/src/xbot/common/injection/RobotModule.java

**Comment by jabrena** [comment]
https://github.com/Team488/SeriouslyCommonLib/blob/master/tests/xbot/common/command/BaseCommandTest.java

**Comment by jabrena** [comment]
https://github.com/Team488/SeriouslyCommonLib/blob/master/tests/xbot/common/controls/sensors/AnalogDistanceSensorTest.java

**Comment by jabrena** [comment]
https://github.com/google/jimfs/blob/master/README.md

**Comment by jabrena** [comment]
http://slides.com/strongback/using-strongback/#/

**Comment by jabrena** [comment]
http://stackoverflow.com/questions/6970192/are-there-any-fake-file-system-frameworks-for-java

**Comment by jabrena** [comment]
http://mockftpserver.sourceforge.net/apidocs/org/mockftpserver/fake/filesystem/FileSystem.html

**Comment by jabrena** [comment]
https://www.google.co.uk/amp/s/garygregory.wordpress.com/2010/01/20/junit-tip-use-rules-to-manage-temporary-files-and-folders/amp/

**Comment by jabrena** [comment]
http://www.programcreek.com/java-api-examples/org.junit.rules.TemporaryFolder
http://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html
http://howtodoinjava.com/junit/junit-creating-temporary-filefolder-using-temporaryfolder-rule/

**Comment by jabrena** [comment]
http://stackoverflow.com/questions/21879804/inject-mocks-for-objects-created-by-factory-classes

**Comment by jabrena** [comment]
https://github.com/ddemidov/ev3dev-lang-fake-sys

**Comment by jabrena** [comment]
Added question to `junit team` about the usage of: File.createTempFile
https://github.com/junit-team/junit4/issues/1469

**Comment by jabrena** [comment]
Unblocked with the Master class of @juan-medina about Mocking.

**Comment by jabrena** [comment]
Ideas:
https://stackoverflow.com/questions/27558284/java-mock-object-without-dependency-injection

**Comment by jabrena** [comment]
FAKE_SYS = os.path.join(os.path.dirname(__file__), 'fake-sys')
https://github.com/rhempel/ev3dev-lang-python/pull/352/files

**Comment by jabrena** [comment]
Added base classes to implement testing for Sensors

**Comment by jabrena** [comment]
https://docs.gradle.org/current/userguide/jacoco_plugin.html

**Comment by jabrena** [comment]
Minimum Level, reached in the last CI build:
https://travis-ci.org/ev3dev-lang-java/ev3dev-lang-java/builds/361212850

```
jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.75
            }
        }
    }
}
```

Now, it is necessary to review Unit Testing syntax in order to close this issue and the issue about testing infrastructure:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/423

**Comment by jabrena** [comment]
Many thanks @juan-medina with this issue.
Now, it is very easy maintain this library for multiple Debian Distros.

Cheers

**Comment by juan-medina** [comment]
@jabrena I think this issue should not be close, until you have an acceptable level of coverage > 85%

**Comment by jabrena** [comment]
hehehe, Oki... :D 

Some days, I added the comment about 0.75... 
but anyway, I will do.

Every comment to improve the quality is welcome and this one goes in that direction. :)

**Comment by jabrena** [comment]
Reached.
https://travis-ci.org/ev3dev-lang-java/ev3dev-lang-java/builds/363201844

Juan Antonio
