### ISSUE TITLE
[CORE] Review BrickPi+ linux problems

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#226]
I have detected some weird behaviour with the system. I am not sure if the problem is BrickPi+, Raspberry Pi 3 or the SD Card.

``` 
[    4.222994] uart-pl011 3f201000.uart: no DMA platform data
[    4.345274] Registered BrickPi line discipline. (28)
[    4.405390] random: nonblocking pool is initialized
[    7.129514] systemd[1]: Unit brickman.service entered failed state.
[    7.401742] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    7.404971] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    7.521663] brcmfmac: brcmf_add_if: ERROR: netdev:wlan0 already exists
[    7.524576] brcmfmac: brcmf_add_if: ignore IF event
[    7.532941] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    7.535967] brcmfmac: power management disabled
[    8.228277] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   14.349549] tty ttyAMA0: Failed to init while setting sensors. (-110)
```

**Comment by jabrena** [comment]
Hi @Dlech, I observed that today in some test, the system is quite slow and the system doesn´t detect the brickpi+ and the ssh connection require 2 tries to connect. Maybe problems with SD Card? how to diagnose? Any clue?

**Comment by jabrena** [comment]
Does exist some way to restart the process with BrickPi+?

**Comment by dlech** [comment]
Trying a different SD card sounds like a good idea.

**Comment by jabrena** [comment]
But why the sd card was degraded? Does the sd card a number of cycles?

**Comment by jabrena** [comment]
https://www.sdcard.org/developers/overview/speed_class/
https://superuser.com/questions/17350/whats-the-life-expectancy-of-an-sd-card

**Comment by jabrena** [comment]
http://ideaheap.com/2013/07/stopping-sd-card-corruption-on-a-raspberry-pi/

**Comment by jabrena** [comment]
I formatted the sdcard without any problem.
It is necessary to install `BatteryMonitor` to avoid this kind of problems.
https://github.com/ev3dev-lang-java/batteryMonitor
