### ISSUE TITLE
[BM] Shutdown without the usage of a Shell

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#247]
http://stackoverflow.com/questions/40351655/how-to-shutdown-reboot-linux-machine-programatically-without-using-commandsrunt/40432406#40432406

**Comment by jabrena** [comment]
Pending of this issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/291

**Comment by JakubVanek** [comment]
One could use systemctl command or a dbus call to achieve that, but we must tweak PolicyKit configuration to allow it (at least that's how it works on Ubuntu).
