### ISSUE TITLE
[CORE] Add Button Support for EV3 Brick

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#273]
```gherkin
Feature: Develop the library EV3Dev-lang-java
In the third generation of Lego Mindstorms, 
it is possible to install a complete Linux distribution and a complete Oracle JRE. 
It is necessary to develop a library to use the hardware compatible with EV3Dev.

    Scenario: Add EV3 Buttons support 
        Given The library EV3Dev-lang-java
        And an EV3 Brick
        Then add the support to use the different buttons that an EV3 Brick has
```

**Technical documentation:**
http://www.lejos.org/ev3/docs/lejos/hardware/Button.html
http://www.lejos.org/ev3/docs/lejos/hardware/Keys.html
http://www.lejos.org/ev3/docs/lejos/hardware/Key.html
http://www.ev3dev.org/docs/kernel-hackers-notebook/ev3-buttons/
http://www.ev3dev.org/docs/tutorials/using-ev3-buttons/#directly-reading-the-event-device

**Implementation ideas:**
https://github.com/mob41/ev3dev-lang-java/blob/develop/src/main/java/org/ev3dev/hardware/Button.java
https://github.com/ev34j/ev34j/blob/master/ev34j-core/src/main/java/com/ev34j/core/buttons/ev3/ButtonType.java
https://github.com/ev34j/ev34j/blob/master/ev34j-core/src/main/java/com/ev34j/core/buttons/ev3/Buttons.java

**Comment by jabrena** [comment]
First test is running.
Integrating initial implementation with LeJOS interfaces

**Comment by jabrena** [comment]
Detected a bug in Button support. It is necessary to review

**Comment by jabrena** [comment]
The issue was solved partially.

In this release we have covered the usage of the button with this Scenario:

``` java
package examples.sensors;

import ev3dev.sensors.Button;

public class ButtonExample {

    public static void main(final String[] args){

        System.out.println("Button example");

        Button.waitForAnyPress();

        System.out.println("Button pressed");
    }
}
``` 

But, it is necessary to research how to increase the granularity in next releases.

**Comment by jabrena** [comment]
Finally, I am using this implementation:
https://github.com/mob41/ev3dev-lang-java/blob/develop/src/main/java/org/ev3dev/hardware/Button.java

@mob41, many thanks for the implementation.

Juan Antonio

**Comment by mob41** [comment]
@jabrena The code idea and implementation can be used as long as you do not claim the code as your own, and follows the terms brought to the MIT License by applying a more restrictive license on the code.

This applies also to the code [LCDGraphics.java, LCD.java, Button.java, and other code licensed](https://github.com/mob41/ev3dev-lang-java/). You should better think about how you will feel if your code that you have paid a lot of time to think a concept to achieve the goal is used by others without proper notice and permission.
