### ISSUE TITLE
Disable Brickman on Startup

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#297]
```gherkin
Feature: Develop the library EV3Dev-lang-java
In the third generation of Lego Mindstorms, 
it is possible to install a complete Linux distribution and a complete Oracle JRE. 
It is necessary to develop a library to use the hardware compatible with EV3Dev.

    Scenario: Disable Brickman in the beginning of a Java process
        Given The library EV3Dev-lang-java
        Then Stop the linux service Brickman in the beginning of execution of the Java process
        And Start again Brickman when the Java process finish
```

http://mylinuxthoughts.blogspot.co.uk/2013/09/processes-daemons-and-signals.html

**Comment by juan-medina** [comment]
http://pubs.opengroup.org/onlinepubs/009695399/functions/kill.html

**Comment by juan-medina** [comment]
https://github.com/jnr/jnr-posix

**Comment by jabrena** [comment]
Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/270

**Comment by jabrena** [comment]
Some Bricks running with `EV3Dev` has a LCD out of the box. 
EV3Dev project includes a visual tool to manage some aspects of the brick, the name Brickman.

If the applications requires to use the LCD, it is necessary to disable brickman.
Besides, it is necessary to enable at the end of the execution in a quiet way.

In java, it is possible execute a logic at the end of any java process, the feature is the following one:

https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)
https://www.tutorialspoint.com/java/lang/runtime_addshutdownhook.htm

Other examples:
https://gist.github.com/jabrena/164f9fee32f554895c1f5bb3d2e6ea63

**Comment by jabrena** [comment]
Video example:
https://www.youtube.com/watch?v=E2MV6_4um0A
