### ISSUE TITLE
[CORE] Review LCD support for PiStorms

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#328]
It is necessary to add LCD support on PiStorms.

Related question:
https://www.mindsensors.com/forum/topic/258_pistorms-v2-ev3dev-graphics-programming

Related Issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/69

http://www.ev3dev.org/docs/platform-comparison/

- [x] Add the feature in the class LCD.java
- [ ] Test on the Brick
- [ ] Notify users in the forum

**Comment by jabrena** [comment]
Related issue on `ev34j`:
https://github.com/ev34j/ev34j/issues/1

**Comment by jabrena** [comment]
I think that this issue requires more research. I will move to next iteration.

**Comment by jabrena** [comment]
https://github.com/ttww/JavaFrameBuffer

**Comment by jabrena** [comment]
https://github.com/ev3dev/ev3dev/issues/961#issuecomment-330002582

**Comment by JakubVanek** [comment]
This might be solved by the new DIsplay API.

**Comment by jabrena** [comment]
Device with poor support.
Rejected by LEAN
