### ISSUE TITLE
Leak resoure

### ISSUE THREAD

**Issue by juan-medina** [ev3dev-lang-java/ev3dev-lang-java#337]
this class need to change https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/master/src/main/java/ev3dev/utils/Sysfs.java

when resources are read it need to use : 

http://docs.oracle.com/javase/7/docs/technotes/guides/language/try-with-resources.html

So basically this

```java
try {
			DataOutputStream out = new DataOutputStream(new FileOutputStream(file));
}
```
should be 

```java
try (DataOutputStream out = new DataOutputStream(new FileOutputStream(file));) {
			
}
```

so if exception happen resources are close

**Comment by jabrena** [comment]
You have reason @juan-medina, but it is not a problem at the moment. All paths used in the class `Sysfs` was certified but the free usage of the class but any user could generate that error.

I will fix the problem.

Juan Antonio

**Comment by jabrena** [comment]
Many thanks to report this issue.
Today, I will try to fix it.

**Comment by jabrena** [comment]
Fixed
