### ISSUE TITLE
[ROS] Subscribe to topic: "cmd_vel" using a message "geometry_msgs.msg/Twist"

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#354]
Develop a ROS Node to subscribe to topic `cmd_vel` which use a Twist message

**Examples:**
https://github.com/andruino/andruinoR2/blob/master/android/andruino_driver/src/es/andruino/andruino_driver/andruinoROS_cmd_vel.java
https://github.com/RCTemp/RCT_Source/blob/master/turtlebot_simple_nav/src/org/ros/android/turtlebot_controller/CmdVelTalker.java
https://github.com/lsa-pucrs/jason-ros-releases/blob/master/projects/scenarios/src/java/jason/architecture/ArtCmdVel.java
https://github.com/aksatshah/head_listener/blob/master/src/listener.py
https://github.com/sc071139/ROS_Mecanum_Node/blob/master/src/tinker_driver/scripts/m1.py

**Comment by jabrena** [comment]
https://github.com/ihmcrobotics/ihmc-open-robotics-software/blob/develop/IHMCROSTools/src/us/ihmc/utilities/ros/publisher/RosOdometryPublisher.java
https://github.com/yamunamaccarana/TCA/blob/master/Navigator/src/tca/RobotDriver.java
https://github.com/jmacglashan/feedback_advantage/blob/master/src/main/java/experiments/turtlebot/TurtleExplorerControl.java
https://github.com/keroma08/lejos/tree/master/ros/nxt_lejos_apps/nxt_lejos_monitor
https://github.com/kylealanr/CS2133/blob/master/Assignment4/Robots/src/RobotInstructor.java
https://github.com/elmot/ev3javabrick/blob/master/ros-ev3-node/src/main/java/elmot/ros/nxt/NXTNode.java
https://github.com/elmot/ev3javabrick/blob/master/ros-ev3-node/src/main/java/elmot/ros/ev3/Ev3Node.java

``` java
        Subscriber<Twist> motorSpeedSubscriber = connectedNode.newSubscriber(namespace.join("cmd_vel"), Twist._TYPE);
        motorSpeedSubscriber.addMessageListener(new MessageListener<Twist>() {
            @Override
            public void onNewMessage(Twist msg) {
                double x = msg.getLinear().getX();
                double y = msg.getAngular().getZ();
                if (Math.abs(x) < 0.02) x = 0;
                if (Math.abs(y) < 0.02) y = 0;
                double s = x < 0 ? -1 : 1;
                double speed = Math.sqrt(x * x + y * y) / Math.sqrt(2);
                double twist = -200 * y / speed;
                speed *= 100 * s;
                try {
                    brick.MOTOR.timeSync(0, MotorFactory.MOTORSET.BC, (int) speed, (int) twist, 1000, MotorFactory.BRAKE.COAST);
                } catch (IOException e) {
                    Ev3Node.this.connectedNode.getLog().error("Motor error", e);
                }
            }
        });

```

**Comment by jabrena** [comment]
http://docs.ros.org/api/geometry_msgs/html/msg/Twist.html

**Comment by jabrena** [comment]
http://wiki.ros.org/geometry_msgs

**Comment by jabrena** [comment]
Now, the bricks are able to be teleoperated in a easy way.

**Comment by RaghavSaxena96** [comment]
how can I send a Twist geometry msg to Ros server  in a eaisest way without knowing much about ros

**Comment by jabrena** [comment]
Hi @RaghavSaxena96, Can you create a new issue about the ROS topic?
