### ISSUE TITLE
Add methods: getRemoteCommand & getRemoteCommands on EV3IRSensor

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#358]
Currently, the class EV3IRSensor has all modes implemented but in `LeJOS` API exist 2 methods pending to implement:

```
int | getRemoteCommand(int chan)Return the current remote command from the specified channel.
void | getRemoteCommands(byte[] cmds, int offset, int len)Obtain the commands associated with one or more channels.
```

It is necessary to add methods: getRemoteCommand & getRemoteCommands in the class: EV3IRSensor.

https://ev3dev-lang-java.github.io/docs/api/latest/ev3dev-lang-java/ev3dev/sensors/ev3/EV3IRSensor.html
http://www.lejos.org/ev3/docs/lejos/hardware/sensor/EV3IRSensor.html
https://github.com/ev3dev-lang-java/lejos-ev3-code-mirror/blob/master/ev3classes/src/lejos/hardware/sensor/EV3IRSensor.java

**Goals:**

- [x] SystemTest the sensor with the implementation of getRemoteCommand
- [x] SystemTest the sensor with the implementation of getRemoteCommands
- [x] Remove getRemoteMode from the sensor
- [x] Added UnitTest for methods

**Comment by jabrena** [comment]
@jartu, Can you review it?

**Comment by jartu** [comment]
Sure, I'll take a look at it.

**Comment by PatrickSalle** [comment]
I use Intelij to compile my programs. In the ev3dev-lang-java:0.7.0.jar 
I have not the getRemoteCommand methods.
What I have to do to get this method?
In my external librairies I refer Gradle:com.github.ev3dev-lang-java:0.7.0

Thank you if you can help me.
Patrick Sallé

**Comment by jabrena** [comment]
Hi @PatrickSalle,

Give me few hours to review this issue, I will give you feedback today.

Juan Antonio

**Comment by jabrena** [comment]
Hi @PatrickSalle, it is true but do you have one example that you need to use that commands?
Tell me.

Cheers

**Comment by PatrickSalle** [comment]
Hi,
I just try to interact with the robot during the execution of program, to
modify
if necesary its behaviour.
Best regards.

2018-02-06 22:47 GMT+01:00 Juan Antonio Breña Moral <
notifications@github.com>:

**Comment by jabrena** [comment]
Hi @PatrickSalle, 

do you have some example using that methods?

Juan Antonio

**Comment by jabrena** [comment]
I found this discussion:
https://lejos.sourceforge.io/forum/viewtopic.php?t=7665

Maybe, it is a good point to begin.

Juan Antonio

**Comment by jabrena** [comment]
https://github.com/mindstorms-cop/lejos-ev3/blob/master/ev3menutools/src/org/lejos/ev3/menutools/ircontrol/RemoteControl.java

**Comment by jabrena** [comment]
https://sites.google.com/site/stanfordpcs/lejos/lejos-exploring-more

**Comment by jabrena** [comment]
https://alwaysbusycorner.com/tag/lejos/

**Comment by jabrena** [comment]
Maybe with this example is enough to add this feature.
I will try to implement this week.

**Comment by PatrickSalle** [comment]
Thank you. I if I really use this feature in a significative example I will
post
the code.


2018-02-07 17:00 GMT+01:00 Juan Antonio Breña Moral <
notifications@github.com>:

**Comment by PatrickSalle** [comment]
I travelled for a long time, and have not work on my project...
Have look at the getRemoteCommand?
Best regards.
Patrick.

**Comment by jabrena** [comment]
One idea to implement the method:

``` java
		// Get the IR commands
			byte [] cmds = new byte[4];
			ir.getRemoteCommands(cmds, 0, cmds.length);
			
			// Figure out which channel is active:
			int command = 0;
			for(int i=0;i<4;i++) {
				if(cmds[i] > 0) {
					channel = i;
					command = cmds[i];
				}
			}
```

**Comment by jabrena** [comment]
Original implementation:
https://github.com/ev3dev-lang-java/lejos-ev3-code-mirror/blob/master/ev3classes/src/lejos/hardware/sensor/EV3IRSensor.java

**Comment by jabrena** [comment]
Hi @PatrickSalle,

I could implement the methods, the solution was not very complicated but I am not able to test in few days. If you have time, I could create a Snapshot to test in your project.

Do you use `Debian Jessie` or `Debian Stretch`?

Juan Antonio

**Comment by jabrena** [comment]
Example to test the feature:

``` 
package example;

import ev3dev.sensors.ev3.EV3IRSensor;
import lejos.hardware.port.SensorPort;
import lejos.utility.Delay;

public class IRTest {

    public static void main(String[] args) {

        EV3IRSensor ir = new EV3IRSensor(SensorPort.S1);
        
        for(int i=0;i<40;i++) {
            System.out.println("cmd " + ir.getRemoteCommand(0)); // gets command from channel 1
            Delay.msDelay(500);
        }

    }

}
```

**Comment by jabrena** [comment]
Example to test the method: `getRemoteCommands`

``` java
package example;

import ev3dev.sensors.ev3.EV3IRSensor;
import lejos.hardware.port.SensorPort;
import lejos.utility.Delay;

public class IRTest2 {

    public static void main(String[] args) {

        EV3IRSensor ir = new EV3IRSensor(SensorPort.S1);

        byte[] commands = new byte[EV3IRSensor.IR_CHANNELS];

        for(int i=0;i<40;i++) {
            ir.getRemoteCommands(commands, 0, commands.length);
            System.out.println("cmd1 " + commands[0]); // gets command from channel 1
            System.out.println("cmd2 " + commands[1]); // gets command from channel 2
            System.out.println("cmd3 " + commands[2]); // gets command from channel 3
            System.out.println("cmd4 " + commands[3]); // gets command from channel 4

            Delay.msDelay(500);
        }

    }

}
```

**Comment by PatrickSalle** [comment]
Merci beaucoup. Comme je suis en voyage, je testerai à mon retour.
Cordialement, Patrick Sallé.

2018-05-04 18:54 GMT+02:00 Juan Antonio Breña Moral <
notifications@github.com>:

**Comment by PatrickSalle** [comment]
Hello,
I have tried to create the EV3IRSensor class with the code
accessible at the address
https://github.com/ev3dev-lang-java/lejos-ev3-code-
mirror/blob/master/ev3classes/src/lejos/hardware/sensor/EV3IRSensor.java
I am not sure that it is the rigth method,
In fact I have no access to UARTPort.

import lejos.hardware.port.UARTPort;


Patrick Sallé.

2018-05-04 19:26 GMT+02:00 Juan Antonio Breña Moral <
notifications@github.com>:

**Comment by jabrena** [comment]
Hi @PatrickSalle,

Can you paste the example that you are trying to test please?

**Comment by PatrickSalle** [comment]
I am using Intellij Idea.
One of my projects is just a test of the main fonctionnalities available in
Ev3dev Lejos.

This project contains  two files :

MyThirdRobot.java with the code to test getRemoteCommand as you have
suggested
EV3IRSensor.java with the code of your implementation of getRemoteCommand.
In this file the

import lejos.hardware.port.UARTPort;

fail.

I enclose a tar of the project :

2018-05-14 20:33 GMT+02:00 Juan Antonio Breña Moral <
notifications@github.com>:
