### ISSUE TITLE
[OpenCV] Detect Color Blob

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#36]
https://github.com/Itseez/opencv/blob/master/samples/android/color-blob-detection/src/org/opencv/samples/colorblobdetect/ColorBlobDetector.java

**Comment by jabrena** [comment]
http://stackoverflow.com/questions/9129037/javacv-blob-detection

**Comment by jabrena** [comment]
https://www.youtube.com/watch?v=bVNYkpH66Hc

**Comment by jabrena** [comment]
http://www.learnopencv.com/blob-detection-using-opencv-python-c/

**Comment by jabrena** [comment]
http://www.technical-recipes.com/2011/track-colored-objects-in-video-using-opencv-and-cvblobslib/

**Comment by jabrena** [comment]
http://m.youtube.com/watch?v=hstdTgiSv8Y

**Comment by jabrena** [comment]
http://8a52labs.com/2011/05/24/detecting-blobs-using-cvblobs-library/

**Comment by jabrena** [comment]
http://answers.opencv.org/question/23207/trying-to-find-center-of-contour-using-color-blob-detection/

**Comment by jabrena** [comment]
http://www.technical-recipes.com/2011/track-colored-objects-in-video-using-opencv-and-cvblobslib/

**Comment by jabrena** [comment]
https://www.quora.com/How-do-I-track-a-car-using-color-detection-and-blob-detection-What-are-the-steps-I-need-to-follow

**Comment by jabrena** [comment]
https://github.com/VMMobility/OpenCV-Color-Blob-Detection/blob/master/OpenCV%20Sample%20-%20color-blob-detection/src/org/opencv/samples/colorblobdetect/ColorBlobDetector.java

**Comment by jabrena** [comment]
http://akaifi.github.io/MultiObjectTrackingBasedOnColor/

**Comment by jabrena** [comment]
https://code.google.com/p/dronelander/source/browse/src/eu/hrasko/dronelander/BlobDetector.java?r=3a4f2f65e377e44d08d7f7691e5165756d3da6da

**Comment by jabrena** [comment]
https://df97e5c8f580f6ac75b80d841f004d5ca19d1b5c.googledrive.com/host/0By56j-W37_RAYS1DcVl3MnFRZGc/index.html

**Comment by jabrena** [comment]
https://github.com/AllNamesAreTaken/BlobDetection/tree/master/BlobDetection/src

**Comment by jabrena** [comment]
https://github.com/Itseez/opencv/blob/master/samples/android/color-blob-detection/src/org/opencv/samples/colorblobdetect/ColorBlobDetector.java

**Comment by jabrena** [comment]
https://github.com/loncaa/Improved-Blob-detection-sample-OpenCV-/blob/master/src/org/opencv/samples/colorblobdetect/ColorBlobDetector.java

**Comment by jabrena** [comment]
https://github.com/CSE455ResistorReader/RedYellowDetection/blob/master/app/src/main/java/com/example/abe/resistorreader/MainActivity.java

**Comment by jabrena** [comment]
http://cell0907.blogspot.com.es/2013/07/tracking-ball-with-javaopencv.html

**Comment by jabrena** [comment]
http://berenoune.blogspot.com.es/2012/10/opencv-android-java-color-detection.html

**Comment by jabrena** [comment]
http://berenoune.blogspot.com.es/2012/10/opencv-c-triangle-detection.html

**Comment by ameysutavani** [comment]
see votchallenge.net also

**Comment by jabrena** [comment]
REJECTED BY LEAN
