### ISSUE TITLE
Convert a LDD Model to STL

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#402]
It is necessary to learn how to convert a `LDD` design into `stl` format to be used by `URDF` models.

Example:
https://github.com/ROBOTIS-GIT/turtlebot3/blob/master/turtlebot3_description/meshes/bases/burger_base.stl

References:
https://youtu.be/7FNUxEfvd48
https://www.shapeways.com/tutorials/exporting-from-blender
https://www.shapeways.com/tutorials/prepping_blender_files_for_3d_printing
https://daler.github.io/blender-for-3d-printing/printing/export-stl.html
https://youtu.be/TaOeQpQMUQo
http://wiki.ldraw.org/index.php?title=LDraw_to_LDD_conversion
https://www.hitechnic.com/downloadnew.php?category=23

**Comment by jabrena** [comment]
https://www.shapeways.com/tutorials/exporting-from-blender

**Comment by jabrena** [comment]
https://www.shapeways.com/tutorials/prepping_blender_files_for_3d_printing

**Comment by jabrena** [comment]
https://daler.github.io/blender-for-3d-printing/printing/export-stl.html

**Comment by jabrena** [comment]
https://youtu.be/TaOeQpQMUQo

**Comment by jabrena** [comment]
http://wiki.ldraw.org/index.php?title=LDraw_to_LDD_conversion

**Comment by jabrena** [comment]
https://www.hitechnic.com/downloadnew.php?category=23

**Comment by jabrena** [comment]
http://wiki.ros.org/urdf/XML/link

**Comment by JakubVanek** [comment]
There is also a format called LDraw. There are many editors for this format. In particular, I think LDCad is better than LDD.

**Comment by JakubVanek** [comment]
Quick google revealed this utility: https://github.com/kristov/ldraw2stl

**Comment by jabrena** [comment]
Rejected by LEAN
