### ISSUE TITLE
How to combine LIDAR data and GPS data?

### ISSUE THREAD

**Issue by JJOCEAN1** [ev3dev-lang-java/ev3dev-lang-java#411]
Good Morning @JJOCEAN1,

Following the discussion from yesterday, I do a summary about your doubt. In your project, you require to store in disk, information from a LIDAR sensor in this case from `RPLIDAR` model and combine with the information about a `GPS` sensor.

Thinking about your doubt, this project could help you in different ways.

**LIDAR Support**
`RPLIDAR`, is a sensor that I have some experience and you could use this library:
https://github.com/ev3dev-lang-java/usb-devices/tree/develop

Examples:
https://github.com/ev3dev-lang-java/ros/blob/develop/src/main/java/examples/Demo6.java
https://github.com/ev3dev-lang-java/ros/blob/develop/src/main/java/examples/CombinedUSBDevices.java
https://github.com/ev3dev-lang-java/ros/blob/develop/src/main/java/examples/ROSPubSubDemo.java

**GPS Support**
In relation to the GPS support, I don´t have a USB support for GPS sensors, but I have created an issue for it.
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/412

At the end you need save in disk information about:

- Timestamp
- Angle
- Distance
- GPS Point

If you observe, in every iteration with the LIDAR, you will have 360 degrees + the information from the GPS.

To solve this problem if you observe, I differenciate between realtime sensors like: Ultrasonic, Motor Encoder, etc... and RPLIDAR which it is necessary to have another approach. In current development I use event-based programming. GPS is another asyncronous sensor so you should combine information in the main thread information asyncronous from 2 sensors:

- RPLIDAR
- GPS

Using this approach offer a solution to not block the main thread.

**Comment by jabrena** [comment]
Doubts about your question:

+ What version do you have about `RPLIDAR`, A1 or A2?
+ What is the goal with the final document? Are you going to process in some way?

How to begin with your development?

This project has been designed to offer a Java solution for Lego Mindstorms EV3. In this generation other provides like Dexter Industries or Mindsensors has created some raspberry products which are compatible with LEGO sensors. All products are compatible with EV3Dev a custom Debian distro. I recommend to start your project installing EV3Dev in your Raspberry Pi 3 board:
http://www.ev3dev.org/docs/getting-started/
http://www.ev3dev.org/downloads/
Download the image for Raspberry Pi 2, it is compatible for Raspberry Pi 3.

**Comment by jabrena** [comment]
How to begin with your development?

This project has been designed to offer a Java solution for Lego Mindstorms EV3. In this generation other provides like Dexter Industries or Mindsensors has created some raspberry products which are compatible with LEGO sensors. All products are compatible with EV3Dev a custom Debian distro. I recommend to start your project installing EV3Dev in your Raspberry Pi 3 board:
http://www.ev3dev.org/docs/getting-started/
http://www.ev3dev.org/downloads/

# Step 1
Download the image for Raspberry Pi 2, it is compatible for Raspberry Pi 3.

**Comment by JJOCEAN1** [comment]
Thanks for your help, first i have an RPLIDAR A1M1-R3, i think about how to create each line in the document, i want (Angle;Distance;latitude;longitude) of each point, it is possible? with that format, separate with (;), the rest of the procces is with this document, but at that moment i only need to create de .txt document

**Comment by jabrena** [comment]
Yes, it is possible combine both async sensors.

**Comment by jabrena** [comment]
Comment in this issue if you find some problem when you try to install EV3Dev for Raspberry Pi 3.

**Comment by jabrena** [comment]
Good morning @JJOCEAN1, 
what OS do you have installed in your laptop? WIN | OSX | Linux

**Comment by jabrena** [comment]
Example to use RPLIDAR:

``` java
package examples;

import ev3dev.sensors.slamtec.RPLidarA1;
import ev3dev.sensors.slamtec.model.Scan;
import lombok.extern.slf4j.Slf4j;

public @Slf4j class Demo {

    public static void main(String[] args) throws Exception {

        log.info("Testing RPLidar on a EV3 Brick with Java");
        final String USBPort = "/dev/ttyUSB0";
        final RPLidarA1 lidar = new RPLidarA1(USBPort);
        lidar.init();

        for(int x = 0; x <= 5; x++){

            final Scan scan = lidar.scan();
            log.info("Iteration: {}, Measures: {}", x, scan.getDistances().size());
            scan.getDistances()
                .stream()
                .filter((measure) -> measure.getQuality() > 10)
                .filter((measure) -> (measure.getAngle() >= 345 || measure.getAngle() <= 15))
                .filter((measure) -> measure.getDistance() <= 50)
                .forEach(System.out::println);
        }

        lidar.close();
        log.info("End demo");
        System.exit(0);
    }
}
```

**Comment by jabrena** [comment]
In the issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/412

You have the info about GPS

**Comment by jabrena** [comment]
Example to use USB GPS:

``` java
package examples;

import ev3dev.sensors.gps.GenericGPS;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class GenericGPSTest {

	public static void main(String[] args) throws Exception {

		final String port = "/dev/ttyACM0";
		final GenericGPS gps = new GenericGPS(port);
		gps.init();

		//This method block main thread 10 seconds
		timeCounter(10);

		gps.close();
		log.info("Closing connection with the USB GPS Device");

		log.info("LAT: {} {}, LAT: {} {}, ALT: {}", gps.getLatitude(), gps.getLatitudeDirection(), gps.getLongitude(), gps.getLongitudeDirection(), gps.getAltitude());
		log.info("DATE: {}, TIMESTAMP: {}", gps.getDate(), gps.getTimeStamp());
		log.info("NSTAT: {}", gps.getSatellitesTracked());

	}

	private static void timeCounter(final int seconds) throws InterruptedException {
		log.info("Start reading");
		for(int x = 0; x <= seconds; x++){
			log.info("Iteration: {} \n\n", x);
			Thread.sleep(1000);
		}
	}
}
```

**Comment by jabrena** [comment]
Hi @JJOCEAN1, any progress?

**Comment by JJOCEAN1** [comment]
Hola @jabrena creo que he conseguido instalar el ev3dev en mi raspberry 3, también a través del software Putty creo que he podido establecer conexión, siguiendo los pasos de http://www.ev3dev.org/docs/tutorials/connecting-to-ev3dev-with-ssh/ , se supone que ¿estando en la misma red wifi es suficiente?, ¿Cuando escribes algún comando dentro de putty, se tiene que actualizar automáticamente y poder ver lo mismo en la raspberry por hdmi?

**Comment by jabrena** [comment]
Hi @JJOCEAN1, 

When you have a `SSH` connection, you could see the result of your commands from `Putty`.
It is not necessary to connect any display to your `Raspberry Pi`.

Did you connect the `RPLIDAR A1` to your Raspberry Pi?

Juan Antonio

**Comment by jabrena** [comment]
On internet exist many Java tutorials, maybe it is a good issue to develop in the future. In part, it is a goal of this educational project in a Robotics context.

To steps to do are:

1. Install Java 10 in local. I suppose that you are using Windows.
2. Install Maven and Gradle
3. Install IntelliJ
4. Download the project example: https://github.com/ev3dev-lang-java/template_project_gradle
5. Open the project on IntelliJ

When you have the previous steps completed, we will continue with more steps.

Juan Antonio

**Comment by JJOCEAN1** [comment]
ok i think i am ready

**Comment by JJOCEAN1** [comment]
Como se ejecuta el codigo de los zip de github y que se ejecute en la raspberry?

**Comment by jabrena** [comment]
Hi @JJOCEAN1, I don't undertand when you say zips of github.

Can you explain in detail your doubt?

If you have the template project in your computer. Open the project with IDEA and add the previous examples that I showed.

In order to deploy the example, you will have to upgrade `MANIFEST-INF` with the name of the class that you want to run and you will have to upgrade the IP of the raspberry pi in the file: `config.gradle`.

Using the Gradle task: `deployAndRun` you can deploy the example in the `Rasperry Pi` and run.

did you install any `JVM` in the Raspberry Pi?

Juan Antonio

**Comment by JJOCEAN1** [comment]
no he instalado ninguna JVM en la raspberry

**Comment by jabrena** [comment]
You sould install a JVM in your board in that case.

```
    apt-key adv --recv-key --keyserver keyserver.ubuntu.com EEA14886
    echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
    echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
    sudo apt-get update
    sudo apt-get install oracle-java8-installer
```

**Comment by jabrena** [comment]
Any progress?

**Comment by jabrena** [comment]
Latest version of the library:

```
https://jitpack.io/#ev3dev-lang-java/usb-devices/0.2.0-SNAPSHOT
```

**Comment by JakubVanek** [comment]
Another way of installing Java (taken from installer):
```sh
    cat >/etc/apt/preferences.d/jdk <<EOF
Package: *
Pin: release a=stable
Pin-Priority: 200
Package: *
Pin: release a=testing
Pin-Priority: 100
EOF
    # workaround for cyclic dependency
    ln -sf "/usr/lib/jvm/java-10-openjdk-armhf/bin/java" "/usr/bin/java"

    # add repo, update
    echo "deb http://ftp.debian.org/debian buster main contrib non-free" | sudo tee "/etc/apt/sources.list.d/jdk.list"
    apt-get update

    # install package
    #  (the symlink above gets discarded, but
    #   it is needed during the installation)
    apt-get install --yes --no-install-recommends "openjdk-10-jre-headless"
```
This process was intended to be run on Debian Stretch, though it may work on Jessie too (just change 'stable' to 'oldstable' in the preferences/jdk part).

**Comment by jabrena** [comment]
Moved question to next release

**Comment by jabrena** [comment]
Any progress @JJOCEAN1 ?

**Comment by jabrena** [comment]
Closed by lack of feedback.
