### ISSUE TITLE
Add a Fake System to simulate the whole ev3dev filesystem

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#423]
In order to improve the Code coverage support, it is necessary the way that we are testing.
https://martinfowler.com/articles/mocksArentStubs.html

> Fake objects actually have working implementations, but usually take some shortcut which makes them not suitable for production (an in memory database is a good example).

How to create folders?
https://www.mkyong.com/java/how-to-create-directory-in-java/

**Comment by jabrena** [comment]
Idea to remove the fake directory recursively:
http://www.baeldung.com/java-delete-directory

**Comment by jabrena** [comment]
Adding Support for Touch Sensors:

```
ev3dev#43|2017-02-18 13:28:57 [main] TRACE ev3dev.hardware.EV3DevPlatform - Detected platform: EV3BRICK
ev3dev#43|2017-02-18 13:28:57 [main] TRACE ev3dev.hardware.EV3DevPlatform - Detected platform: EV3BRICK
ev3dev#43|2017-02-18 13:28:57 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detecting motors with port: in1
ev3dev#43|2017-02-18 13:28:58 [main] DEBUG ev3dev.utils.Sysfs - ls /sys/class/lego-sensor
ev3dev#43|2017-02-18 13:28:58 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor3/address
ev3dev#43|2017-02-18 13:28:58 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detected port on path: /sys/class/lego-sensor/sensor3/address
ev3dev#43|2017-02-18 13:28:58 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/lego-sensor/sensor3/value0
ev3dev#43|2017-02-18 13:28:58 [main] INFO  examples.sensors.ev3.TouchSensorDemo - Iteration: 0
ev3dev#43|2017-02-18 13:28:58 [main] INFO  examples.sensors.ev3.TouchSensorDemo - Touch: 0
```

**Comment by jabrena** [comment]
Added support.

Reviewed example from example repo:

``` java
package ev3dev.sensors.ev3;

import ev3dev.sensors.Battery;
import lejos.hardware.port.SensorPort;
import lejos.robotics.SampleProvider;
import lejos.utility.Delay;

public class TouchSensorDemo {

	//Robot Configuration
	private static EV3TouchSensor touch1 = new EV3TouchSensor(SensorPort.S1);
	
	//Configuration
	private static int HALF_SECOND = 500;
	
	public static void main(String[] args) {



		final SampleProvider sp = touch1.getTouchMode();
		int touchValue = 0;

        //Control loop
        final int iteration_threshold = 20;
        for(int i = 0; i <= iteration_threshold; i++) {

        	float [] sample = new float[sp.sampleSize()];
            sp.fetchSample(sample, 0);
            touchValue = (int)sample[0];

			System.out.println("Iteration: {}" + i);
			System.out.println("Touch: {}" + touchValue);
            
            Delay.msDelay(HALF_SECOND);
        }

        System.out.println(Battery.getInstance().getVoltage());
		
	}

}
```
https://github.com/ev3dev-lang-java/examples/blob/master/ev3dev-lang-java/src/main/java/ev3dev/sensors/ev3/TouchSensorDemo.java

**Comment by JakubVanek** [comment]
IIRC this might be done using service providers, too.
Extra-advanced option would be to write a custom FUSE filesystem creating an illusion of the real brick.

**Comment by jabrena** [comment]
Hi @JakubVanek, current solution is Java based and it is easy to maintain.
Current solution is based on a static file system simulation for the tests. 
For `ev3dev-lang-python` exist a similar solution:
https://github.com/ev3dev/ev3dev-lang-fake-sys

I think that current implementation is Ok for static sensor simulations.

**Comment by jabrena** [comment]
Development complete.
It is necessary to review current implementation to try to refactor de code a bit.

**Comment by jabrena** [comment]
Refactored code.

In the future, this development should be isolated in a new repo with new features like:

- Dynamic Sensor behaviours

But for the moment is Ok.
