### ISSUE TITLE
Externalise EV3Dev constants to offer support for multiple EV3Dev Distros (Jessie & Stretch)

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#443]
Currently, the main library has support for `Debian Jessie` and `Debian Stretch` for `EV3Dev` but the support is stored in 2 different Git Branches. It is necessary to unify to minimize the effort to maintain.

Analyzing the changes in the library, you observe the number of changes are not huge so, it is possible to find a good solution with not so much effort.

It is necessary to find that solution.

- [x] Detect distro [Jessie | Stretch ]
- [x] Externalize data with changes in ev3dev (A possible solution is the usage of property files)
- [x] Review possible changes in some classes to support both distros
- [x] Review possible changes in some tests

**Comment by JakubVanek** [comment]
This might be done using Jigsaw and service providers.

**Comment by jabrena** [comment]
Yes, but I was thinking in the properties to have support for jessie and stretch.

**Example:**

Jessie:
/sys/class/power_supply/legoev3-battery

Stretch:
/sys/class/power_supply/lego-ev3-battery

Using 2 property files it is possible to load the right properties:

```
robot@ev3dev:~$ cat /etc/os-release
PRETTY_NAME="ev3dev-stretch"
NAME="ev3dev-stretch"
ID=ev3dev
ID_LIKE=debian
HOME_URL="http://www.ev3dev.org"
SUPPORT_URL="http://www.ev3dev.org/support"
BUG_REPORT_URL="https://github.com/ev3dev/ev3dev/issues"
```

**Comment by jabrena** [comment]
Reviewing the UML design the right class candidate to add a new method `getDistro` is **EV3DevPlatforms.java**

The new method could return:

- JESSIE
- STRETCH

The possible values will be stored in a Enum

If the class doesn´t detect one of the distro will raise a RuntimeException.

**Comment by jabrena** [comment]
Later, it is necessary to analyse how to load in a property file all elements.

Related links:
https://stackoverflow.com/questions/12473537/naming-convention-for-properties-in-property-file

**Comment by jabrena** [comment]
How to reset a static field? (Reflection problem)
https://stackoverflow.com/questions/26234742/resetting-static-fields-for-junit-tests
https://caffinc.github.io/2015/12/static-final-java-junit-test/
https://blog.box.com/blog/unit-testing-with-static-variables/

**Comment by jabrena** [comment]
It is necessary to identify the changes between Jessie Support & Stretch Support.

- [ ] **Sound:** In this case, exist 2 different implementations. The main problem in Stretch, is the lack of a volume endpoint.
- [ ] LED: Different paths. Unify paths and the way to build the final paths.
- [ ] EV3DevPlatforms: Platform, Motor Ports & Sensor Ports
- [ ] BaseSensor: SwitchDelay
- [ ] Battery:
- [ ] EV3Key: event path
- [ ] FakeBattery:
- [ ] FakeLegoSensor:
- [ ] FakeUnregulatedMotor:
- [ ] FakeRegulatedMotor:
- [ ] FakeLargeRegulatedMotor:

Some tests:

- [ ] ShellTest
- [ ] EV3DevPlatformsTest
- [ ] EV3SensorDeviceTest

**Comment by jabrena** [comment]
I will continue with the changes.

**Comment by jabrena** [comment]
It is necessary to review some classes that raises some exceptions in Travis.

**Comment by jabrena** [comment]
Added support.

**Comment by jabrena** [comment]
Finally, the library in the last version only support Debian Stretch. Doesn't any value to maintain 2 distros.
