### ISSUE TITLE
Add support for Bluetooth

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#446]
It might help with https://github.com/ev3dev-lang-java/installer/issues/3. EV3 discovery should be better doable in Java than in would be in Bash.

**Comment by jabrena** [comment]
Example:
https://youtu.be/brfgF3D5c4k

**Comment by jabrena** [comment]
Idea:
https://github.com/ev3dev/ev3dev-lang-python/issues/137

If we can connect a `PS4 Controller` or a `Wiimote`, it could be a good milestone.

**Comment by jabrena** [comment]
https://github.com/williamahartman/Jamepad

**Comment by JakubVanek** [comment]
Potential alternatives to the leJOS Bluetooth stack:
https://github.com/olir/lbt4j
https://github.com/hypfvieh/bluez-dbus

**Comment by jabrena** [comment]
Rejected by LEAN
