### ISSUE TITLE
Generate .sh files to run jar from Brickman

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#467]
**Why:**
One scenario to execute the applications is using the `Gradle` tasks from the project which they were designed to deploy and run a `FatJar`. 
https://github.com/ev3dev-lang-java/template_project_gradle

Another scenario could be deploy only the application and execute the Java artifact (.jar) from the `EV3Dev` menu (Brickman)

**Requirement:**
It is necessary to review how to update the `Gradle` tasks from `template_project_gradle` to generate/update a file named: `"launchJava.sh" `with execution permissions to be used by `Brickman`.

In that way, the `Gradle` process deploy the Jar file and the `Bash` script named `"launchJava.sh"` to be used by Brickman.

What is the benefit of this issue? Run Java applications from `Brickman` in an easy way.

**Some ideas:**
https://stackoverflow.com/questions/41712119/how-to-generate-an-executable-sh-file-with-gradle?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
https://askubuntu.com/questions/229589/how-to-make-a-file-e-g-a-sh-script-executable-so-it-can-be-run-from-termina?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
https://docs.gradle.org/current/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html

**Comment by JakubVanek** [comment]
You can do something like this, it would just invoke java runtime instead of dynamic linker:
https://github.com/ev3dev-lang-java/openjdk-ev3/blob/eda19d85ec79c87d06fb1194dbd1a91fc8faf2b1/scripts/lejos/wrapper.sh

**Comment by JakubVanek** [comment]
We can use binfmt-misc too. Then we wouldn't need per-file wrappers, you could run `.jar` directly. You would just set jar files (or jmods?) to be executed with our central wrapper.
https://wiki.archlinux.org/index.php/Binfmt_misc_for_Java

**Comment by JakubVanek** [comment]
If a power user wanted to pass his own JVM flags, he could just copy a customized wrapper to `/home/robot`.

**Comment by jabrena** [comment]
Current prototype:

``` java
robot@ev3dev:~$ cat launchJava.sh
java -jar template_project_gradle-all-2.1.0-SNAPSHOT.jar
chmod +x ./launchJava.sh 
```

**Comment by jabrena** [comment]
Hi @JakubVanek, maybe with this idea we could begin. It is simple. :)

**Comment by JakubVanek** [comment]
Ok, but binfmt-misc is simple too (when following the guide on Arch WIki).

**Comment by jabrena** [comment]
Development done.
Pending regression test with Brick:

``` groovy
task deploy << {
    ssh.run {
        session(remotes.ev3dev) {
            println "scp " + "${rootProject.name}" + "-all-" + version + ".jar " +  remotes.ev3dev.user + "@" + remotes.ev3dev.host + ":/home/robot"
            put from: "./build/libs/" + "${rootProject.name}" + "-all-" + version + ".jar", into: "/home/robot/"
            execute "java -jar " + "${rootProject.name}" + "-all-" + version + ".jar > launchJava.sh"
            execute "chmod +x ./launchJava.sh"
        }
    }
}
```

**Comment by JakubVanek** [comment]
Hmmm, could you upload `.jar`s to another directory, let's say `/home/robot/jars`? That would prevent accumulation of mess in the home directory.

In the future, we might be also interested in running Java 9 jmods.

Also, why aren't you creating per-file scripts instead of one global script? What if I need to execute two different JARs? I could easily have an app and a standalone configuration tool (hmmm, more on that later...).

**Comment by jabrena** [comment]
The idea about jars, totally agree.
The idea to create multiple .sh ok, but I need to see how to identify every jar. I suppose that the META-INF should be generate on-fly. If you like for this iteration we go with a global script and in v0.9.0 we think in a way to have multiple scripts.

**Comment by JakubVanek** [comment]
Well, the user should create his own manifest (and each JAR should have its own name). The main class name is stored in the manifest, so there shouldn't be a problem (JVM loads it for us).

I don't think a global script is a good idea at all. I can imagine a pretty realistic situation, where a team on a competition wants to have two separate strategies. Having two different JARs would make the switch between programs easy.

**Comment by jabrena** [comment]
The case that you say, is right, in FLL, people execute 4 programs +-

**Comment by jabrena** [comment]
Tested with success.

**Comment by jabrena** [comment]
@JakubVanek, if you like in the next iteration, we will create an issue to extend this feature to support multiple .sh launchers.

**Comment by JakubVanek** [comment]
Delivered in the recent template project changes.
