### ISSUE TITLE
Upgrade Installer to Install OpenJDK 11 for BrickPi,BrickPi3 & PiStorms

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#477]
It is necessary to upgrade the following bash Script to allow installing latest Java version.

``` bash
function installJavaForBrickPi() {
    apt-key adv --recv-key --keyserver keyserver.ubuntu.com EEA14886
    echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
    echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
    apt-get update
    apt-get install --yes --no-install-recommends oracle-java8-installer
    java -Xshare:dump

    #Review in the future how to accept licence automatically
    #https://askubuntu.com/questions/190582/installing-java-automatically-with-silent-option
}
```

**Comment by JakubVanek** [comment]
Hmmm... could you integrate [my rework](https://github.com/JakubVanek/elj-install/blob/5d7df33209fb9a5d446642cc8d70e23f17d504a4/modules/java.sh) first? I think it will make the code cleaner. I could do it myself, but I'd need commit privileges.

IDK about the compatiblity of EV3 binaries, but we've disabled multiprocessing and rpi has multicore processor. It might run, it might crash. And floating point ops will be much slower compared to native build.

We can try to download Debian Buster deb packages (or add its APT repo + override). It might depend on more packages, that has to be tested.
https://packages.debian.org/buster/armhf/openjdk-10-jre-headless/download

**Comment by JakubVanek** [comment]
Rework PR submitted. https://github.com/ev3dev-lang-java/installer/pull/18

**Comment by jabrena** [comment]
Next week, I will merge everything.

**Comment by jabrena** [comment]
Merged.
Testing pending on Brickpi3

**Comment by JakubVanek** [comment]
The installer now installs `openjdk-11-jre-headless`.

**Comment by JakubVanek** [comment]
Done.
