### ISSUE TITLE
Create a Testing Lab

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#479]
**Problem to solve:**

- Accelerate release certification process.

**Problem description:**

The project continue adding process to increase the quality of the deliverables but at the end of the process, one human has to ensure that the library run on the devices. One interesting idea could be have a physical installation with:

- Small computer (Save energy) with Jenkins installed
- EV3 Brick with a Operating system to certificate + Sensors/Actuators connected

From the Small computer a Jenkins job could be launched once the system detect a new event from the SCM and in that moment, Jenkins send a set of physical tests to run on the device.

**Similar ideas:**
https://codelabs.developers.google.com/codelabs/cloud-test-lab/index.html?index=..%2F..%2Findex#0
http://www.datacenterdynamics.com/content-tracks/design-build/facebook-runs-massive-mobile-test-lab-in-prineville-data-center/96594.fullarticle

**Inventory:**

- [x] EV3 Brick with Debian Jessie installed
- [x] EV3 Brick with Debian Stretch installed (Snapshot)
- [x] 2x USB 2.0 hub
- [x] 2x Wifi Dongle

**Comment by JakubVanek** [comment]
Hmmm, a testing lab platform:
* the EV3 testing platform could boot off a USB flash drive (maybe only as a bootloader?). That would flash the SD card with new ev3dev images and install java and the testing tools.

Regarding the continuous-"build" stack:
* OS: we don't touch that, we'd just download the latest snapshot.
* JVM: it could be built using some more powerful SBC, maybe ODROID HC2. Travis might be sufficient.
* Library: that could be handled using ODROID too. Travis might be sufficient.

**Comment by jabrena** [comment]
https://www.techcoil.com/blog/how-i-setup-jenkins-on-my-raspberry-pi-3-with-raspbian-stretch-lite/

**Comment by JakubVanek** [comment]
Hmmm, you could run Jenkins JNLP slave on the EV3.

**Comment by jabrena** [comment]
Added Testing lab:

**Network:**

- Domestic Router
- 4x Ethernet cable
- 2x USB Ethernet adapter for EV3

**Bricks:**

- EV3 + EV3Dev Debian Jessie
- EV3 + EV3Dev Debian Stretch
- BrickPi+ Raspberry Pi 3 | Raspberry Pi 3 Model B+
- BrickPi3 + Raspberry Pi 3

**Comment by jabrena** [comment]
Using this infrastructure, it is possible to improve the testing for the project in this iteration.
