### ISSUE TITLE
Verify that OpenCV works out-of-the-box on Jessie

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#509]
Details in this issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/502

**Comment by JakubVanek** [comment]
Yes. I have installed a clean Jessie armel chroot on an armv7 box. Then I installed the EV3 java & opencv libs, both through our installer. Then I managed to run HelloWorldCV successfully.
