### ISSUE TITLE
Review the idea about executable jars for linux

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#516]
https://coderwall.com/p/ssuaxa/how-to-make-a-jar-file-linux-executable

**Comment by JakubVanek** [comment]
Hmmm, that is a great idea! We then wouldn't need separate shell script wrapper for each jar file.

**Comment by jabrena** [comment]
Yes, exactly.
I suppose that the implementation in gradle should not be very hard

**Comment by JakubVanek** [comment]
I was thinking how we can run JARs from Brickman:
1. The new Java package includes a file for a so called binfmt_misc, which, when combined with binfmt-support package from debian, can directly execute java jars (like ./hello.jar), given that they have the executable flag set.
2. openjdk-system integration, but now I'm wondering if it is not unnecessarily complicated.
3. Creating a shell script in template_project_gradle which would work as a launcher for a jar somewhere not directly in /home/robot.

(3) seems the simplest, the user could also edit the wrapper easily. There might however be problems with that the icon in brickman != the jar itself, but I'm not sure how real such a scenario is.

**Comment by jabrena** [comment]
Yes, we encapsulate the functions in installer and later call from template project.

I will this weekend a prototype. Maybe later, I will need your help with the call from Installer to execute the AppCDS. 

Using this technique, any user who deploy a HelloWorld should execute in less than 5 seconds. From the current 60 seconds.

**Comment by jabrena** [comment]
I will test adding the following JVM flags:

`-noverify -XX:TieredStopAtLevel=1`

Source: http://presos.dsyer.com/decks/how-fast-is-spring.html

**Comment by JakubVanek** [comment]
Delivered via shell script wrapper.
