### ISSUE TITLE
Installer Script Fails On EV3 Due To Typo In Platform Detection

### ISSUE THREAD

**Issue by MindS1** [ev3dev-lang-java/ev3dev-lang-java#517]
**Platform**: EV3
**OS**: ev3dev based on Debian Jessie
**Problem**: After setting up an EV3 install and following the instructions shown [here](https://github.com/ev3dev-lang-java/installer), running the latest installer.sh fails with "Platform detected: unknown".  

![capture](https://user-images.githubusercontent.com/6912922/43231462-7f53d250-903a-11e8-8edd-3a0ac5a597c2.PNG)  

**Solution**
I believe the issue can be resolved by fixing a minor **typo** in the "vars.sh" installer module: [https://raw.githubusercontent.com/ev3dev-lang-java/installer/develop/modules/vars.sh](https://raw.githubusercontent.com/ev3dev-lang-java/installer/develop/modules/vars.sh)  

Currently:
BATT_EV3="/sys/class/power_supply/lego-ev3-battery"
Should be:
BATT_EV3="/sys/class/power_supply/legoev3-battery"

Can be verified by navigating to that directory on the EV3:
![capture2](https://user-images.githubusercontent.com/6912922/43231654-434692ec-903b-11e8-9920-e609b73b1943.PNG)

**Comment by jabrena** [comment]
Hi @MindS1, sorry by the delay I didnt see the alert.
Try to use master branch. Master is for Jessie, Develop is for Stretch.

**Comment by jabrena** [comment]
And welcome to this project with your WIN environment :)

**Comment by jabrena** [comment]
Did my comment solve your doubt?

**Comment by MindS1** [comment]
Yes, thanks for figuring that one out. I wasn't aware there were different installer versions.
