### ISSUE TITLE
Create an Architecture Decision Record (ADR) document

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#521]
After reading this tweet:
https://twitter.com/nicolas_frankel/status/1029093247497461761

I noticed that the project should include some kind of technical documentation to store some decision taken in the project.

**Comment by JakubVanek** [comment]
ADR note: to have a simple solution for printing logs when running from Brickrun (#494), use of `System.out` is discouraged. `System.err` or SLF4J should be used instead.

**Comment by jabrena** [comment]
Allrighty

**Comment by jabrena** [comment]
I will follow the following structure:
https://github.com/joelparkerhenderson/architecture_decision_record

- /docs/adr/adr_name.md

**Comment by JakubVanek** [comment]
I added the Sensor ADR and the Display API ADR. I also tweaked a bit the other ADRs.

**Comment by jabrena** [comment]
Added
