### ISSUE TITLE
Review units for method: setSpeed(int speed)

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#525]
It is necessary to review the range of values for method `setSpeed` for a tacho motor.

![](http://ev3dev-lang-java.github.io/docs/support/fundamentals/actuators/ev3_large_motor.png)

https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/develop/src/main/java/ev3dev/actuators/lego/motors/BaseRegulatedMotor.java

``` java
    /**
     * Sets desired motors speed , in degrees per second;
     * The maximum reliably sustainable velocity is  100 x battery voltage under
     * moderate load, such as a direct drive robot on the level.
     * @param speed value in degrees/sec
     */
    public void setSpeed(int speed) {
        this.speed = speed;
		if (!this.regulationFlag) {
            this.setIntegerAttribute(DUTY_CYCLE, speed);
		} else {
            this.setIntegerAttribute(SPEED, speed);
        }
    }
```

http://ev3dev-lang-java.github.io/docs/api/latest/ev3dev-lang-java/ev3dev/actuators/lego/motors/BaseRegulatedMotor.html

```
public void setSpeed(int speed)
Sets desired motors speed , in degrees per second; 
The maximum reliably sustainable velocity is 100 x battery voltage under moderate load, such as a direct drive robot on the level.
Parameters:
speed - value in degrees/sec
```

http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/motors.html#tacho-motor-subsystem

```
count_per_rot | read-only | 
Returns the number of tacho counts in one rotation of the motor. 
Tacho counts are used by the position and speed attributes, 
so you can use this value to convert from rotations or degrees to tacho counts. 
(rotation motors only)

count_per_m | read-only | 
Returns the number of tacho counts in one meter of travel of the motor. 
Tacho counts are used by the position and speed attributes, 
so you can use this value to convert from distance to tacho counts. 
(linear motors only)

speed | read-only | 
Returns the current motor speed in tacho counts per second. Note, this is not necessarily degrees (although it is for LEGO motors). 
Use the count_per_rot attribute to convert this value to RPM or deg/sec.

speed_sp | read/write | 
Writing sets the target speed in tacho counts per second used for all run-* commands except run-direct. Reading returns the current value. 
A negative value causes the motor to rotate in reverse with the exception of run-to-*-pos commands where the sign is ignored. 
Use the count_per_rot attribute to convert RPM or deg/sec to tacho counts per second. 
Use the count_per_m attribute to convert m/s to tacho counts per second.
```

Interesting links:
https://github.com/ev3dev/ev3dev-lang-python/issues/220

**Comment by jabrena** [comment]
**Business Rule:**
It is necessary to create some kind of input validation to avoid values greater than 900.

**Comment by JakubVanek** [comment]
Please do not do that. It is possible to achieve higher speeds. I have tried to mix 3 NiMH batteries with 3 NiZn batteries and the motors really had higher peak speeds. I have not measured the RPM, but the buzzing noise had higher pitch. If the speed is higher than maximum, the motor regulator will probably keep them on 100 % of time, which is OK.

**Comment by jabrena** [comment]
Oki.

The essence of this issue was to review the units sent from LeJOS interface to EV3Dev runtime but everything is Ok. I was checking it because exist some possible projects in the air to interact with SLAM subsystems and it is important the accuracy between `tacho counts`and other metrics.

Maybe, I should invest more time in documentation about Motor theory for Differential model.

**Comment by jabrena** [comment]
Reviewed
