### ISSUE TITLE
Refactor Path syntax

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#532]
Review Paths in the project following the comment from @JakubVanek 

```
/* GOOD  */ Paths.get("/tmp", "abcd")
/* BAD:  */ Paths.get("/tmp" + "/" + "abcd")
```

**Comment by JakubVanek** [comment]
This is probably not necessary. The only place where this would create problems is Windows and even there, forward slashes work sometimes.
