### ISSUE TITLE
Release process v0.9.0

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#543]
Once the development process was completed, it is necessary to review the Schedule planned

# Artifacts

**Debian Jessie & Stretch:**

- [x] installer (develop branch) v2.2.2
- [x] ev3dev-lang-java v2.4.16
- [x] template-project-gradle v2.4.16
- [x] JVM: OpenJDK 11 JRI
- [x] JVM: OpenJDK 12 JRI EA

# Documentation 

- [x] Readme ev3dev-lang-java
- [x] API upgrade 
- [x] Website upgrade https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/481
- [x] Docs  https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/408 https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/407 https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/331

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/482

**Comment by JakubVanek** [comment]
Hmmm, I now have the brick returned, but I have lost my sd card, so I will have to buy one tomorrow.

**Comment by jabrena** [comment]
Tomorrow :p

**Comment by jabrena** [comment]
Installer Released

**Comment by jabrena** [comment]
Problem with the release:
https://github.com/jitpack/jitpack.io/issues/3552

**Comment by jabrena** [comment]
Upgrading Website

**Comment by jabrena** [comment]
Website upgrade

**Comment by jabrena** [comment]
Pending docs for tomorrow

**Comment by jabrena** [comment]
Problem with the release again:
https://github.com/jitpack/jitpack.io/issues/3555

Pending from a solution from Jitpack :(

**Comment by jabrena** [comment]
Detected problem:
https://github.com/jitpack/jitpack.io/issues/3559

Jitpack need to downgrade to OpenJDK 10 to run Gradle
https://github.com/jitpack/jitpack.io/issues/3559

**Comment by jabrena** [comment]
Published correctly.
https://jitpack.io/com/github/ev3dev-lang-java/ev3dev-lang-java/2.4.16/build.log

In the future, if some build fail, it is very pragmatic to write support people of Jitpack. The support is fantastic.

**Comment by jabrena** [comment]
Updating docs

**Comment by jabrena** [comment]
Question about choco:
https://github.com/chocolatey/choco/issues/1677

**Comment by jabrena** [comment]
Documentation updated
