### ISSUE TITLE
Update platform specs in README

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#545]
Hi,

I think the platform comparison table should be corrected. My proposal follows:

| # | Element  | EV3 P-Brick                                                                                  | Raspberry Pi 3 Model B+          |
|---|----------|------------------------------------------------------------------------------------------|----------------------------------|
| 1 | Platform | EV3 Brick                                                                                | BrickPi+,  BrickPi3, PiStorms      |
| 2 | SoC      | TI Sitara AM1808                                                                  | Broadcom BCM2837 |
| 3 | CPU      | 1× ARM926EJ-S @ 300MHz ([max 456MHz][1])                                                                              | 4× ARM Cortex-A53 @ 1400MHz        |
| 4 | RAM      | 64 MB LPDDR | 1024 MB LPDDR2 (900 MHz)             |
| 5 | USB Host     | 1× USB 1.1  (without onboard hub)                                                              | 4× USB 2.0 (from onboard hub)                              |
| 6 | Year     | 2010                                                                                     | 2018                             |

The most problematic thing is the amount of RAM available on EV3: `16KB of Instruction Cache, 16KB of Data Cache, 8KB of RAM (Vector Table), 64KB of ROM` => 40 kB of special-purpose RAM + 64 kB ROM. The RAM size wasn't mentioned.

[1]: https://lechnology.com/2018/06/overclocking-lego-mindstorms-ev3-part-2/

Regards

**Comment by jabrena** [comment]
It is perfect. 

Create a branch from #443 with the change and we will merge next week.

**Comment by jabrena** [comment]
Merged
