### ISSUE TITLE
Install LeJOS firmware to a RCX brick from EV3 brick/PiStorms/BrickPi+ with EV3Dev

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#56]
A EV3 Brick with EV3Dev is a full featured Linux OS so, it is necessary to test if it possible to install LeJOS firmware to a RCX Brick from EV3 following this document:
https://minordiscoveries.files.wordpress.com/2017/01/rpi_rcx.pdf

**Comment by jabrena** [comment]
http://mindsensors.ddns.net/index.php?module=pagemaster&PAGE_user_op=view_page&PAGE_id=59

**Comment by jabrena** [comment]
http://www.lejos.org/p_technologies/nxt/nxj/api/lejos/nxt/RCXLink.html

**Comment by jabrena** [comment]
http://www.lejos.org/nxt/nxj/tutorial/Communications/Communications.htm

**Comment by jabrena** [comment]
http://www.drvegetable.com/irremote_protocol.html

**Comment by jabrena** [comment]
http://www.hitechnic.com/cgi-bin/commerce.cgi?preadd=action&key=nil1046

**Comment by jabrena** [comment]
http://www.mindsensors.com/ev3-and-nxt/123-pf-motor-controller-for-nxt-or-ev3-pfmate

**Comment by jabrena** [comment]
http://blog.hsh.one.pl/?p=210

**Comment by jabrena** [comment]
http://www.lejos.org/forum/viewtopic.php?t=7633

**Comment by jabrena** [comment]
https://www.cs.kent.ac.uk/pubs/2002/1517/content.pdf
ftp://ftp.oreilly.com/pub/conference/java2001/Knudsen_leJOSpresent.pdf
https://www.usenix.org/legacy/event/usenix2000/freenix/nikander/nikander.pdf
http://scripts.cac.psu.edu/users/r/e/ree5047/research/lejos/lejosProgramming.pdf
ftp://ftp.dca.fee.unicamp.br/pub/docs/gudwin/LEGO%20Mindstorms/Syngress%20-%20Programming%20Lego%20Mindstorms%20with%20Java.pdf
http://willsmc.com/robotics/rcx/rcx.html

**Comment by jabrena** [comment]
http://clark.cementhorizon.com/RCX-web-page-2013-09-29.html

**Comment by jabrena** [comment]
http://cs.brown.edu/courses/cs148/old/2004fall/brickOS/HOWTO/lnp.html

**Comment by jabrena** [comment]
https://minordiscoveries.wordpress.com

**Comment by jabrena** [comment]
http://www.extremenxt.com/lego.htm#sensors

**Comment by jabrena** [comment]
http://www.mralligator.com/rcx/index.html

**Comment by jabrena** [comment]
http://www.philohome.com/sensors/gp2d12.htm

**Comment by jabrena** [comment]
http://www.cs.ru.nl/lab/rcx/experiments/1.Proximity/Proximity.html

**Comment by jabrena** [comment]
http://www.cs.ru.nl/lab/rcx/

**Comment by jabrena** [comment]
http://www.techno-stuff.com/IRRD.htm

**Comment by jabrena** [comment]
https://seriousrobotics.wordpress.com/2011/11/20/using-rcx-lego-sensors-with-arduino/

**Comment by jabrena** [comment]
http://www.instructables.com/id/Use-LEGO-Mindstorm-RCX-Light-Sensor-with-Arduino-P/?ALLSTEPS

**Comment by jabrena** [comment]
http://www.philohome.com/nxtcables/nxtcable.htm

**Comment by jabrena** [comment]
http://battle-bot.blogspot.com.es/2012/10/unobot.html

**Comment by ameysutavani** [comment]
Hello,
I can confirm that it is definitely possible to load lejos firmware to RCX from raspberry pi(running raspbian jessie). I have tried this with standard lego usb IR tower and also with a self made serial tower (using 555 for generating 38kHz pulse and FTDI cable for usb serial port). I can share the circuit diagram if anyone is interested.

However, I was not able to compile lejos programs (error being not able to locate java.lang classes). I can try and replicate the error again and share console log if anyone wants to try.

As for ev3dev, I think it should yield same outcome as that of raspbian as they are quite similar.

**Comment by jabrena** [comment]
Hijo @ameysutavani,

Congratultions! 

If you could test with EV3Dev,  it could be great. In a near future,  I will add mini site to add docs and experiences with this project. If you test it,  we could share the experience with other mates. 

Congrats!! 

Cheers

**Comment by jabrena** [comment]
In what parts of the project,  are you interested?

**Comment by ameysutavani** [comment]
Hello @jabrena 
Sorry for the late reply, was travelling.

> If you could test with EV3Dev, it could be great.

Currently I don't have access to mu EV3 brick; I will test on it as soon as possible.

> In what parts of the project, are you interested?

No specific interests as such; however I would like to work in area with overlapping ev3 and android smartphones.

**Comment by jabrena** [comment]
Yes,  web could play with Android using Akka. We could create a remote control from Android using Akka. Do you like the challenge?

**Comment by jabrena** [comment]
Take a look Akka:
http://es.slideshare.net/mobile/remeniuk/first-glance-at-akka-20

**Comment by jabrena** [comment]
http://es.slideshare.net/mobile/frodriguezolivera/concurrent-and-distributed-applications-with-akka-java-and-scala-39130140

**Comment by jabrena** [comment]
https://www.google.es/url?sa=t&source=web&rct=j&url=https://courses.cs.ut.ee/MTAT.08.009/2013_fall/uploads/Main/2013DS-L010.pdf&ved=0ahUKEwjT0vu2t5LLAhVEPBQKHQ8HAnk4ChAWCDMwCA&usg=AFQjCNEpY2ITumoeXVzUSlXcQl15yrq9VQ&sig2=avjTHXdtE2PkVp3ORrVi0g

**Comment by jabrena** [comment]
Hi @ameysutavani, If you like the idea, I will create a new issue about Remote Control.
I am thinking to create a Github organization to create sub repositories for other developments. One repository could be the development of a remote control using Android.

**Comment by ameysutavani** [comment]
Hi @jabrena seems like a good idea. I dont have any prior knowledge of Akka though. I am currently exploring different ways to run an opencv app on android (to do slam) and command a robot made of ev3 accordingly. (I know this can be done with lejos's remote api, however i would like to do something similar in c++). If you like the idea, we can explore further.

**Comment by jabrena** [comment]
Take a look this issue:
https://github.com/ev3dev-lang-java/remote/issues/1

**Comment by jabrena** [comment]
Later, I will test it, but it is a offtopic issue.

**Comment by jabrena** [comment]
https://forum.arduino.cc/index.php?topic=370010.0

**Comment by jabrena** [comment]
http://phillipecantin.blogspot.co.uk/2012/08/a-new-life-for-rcx-20.html

**Comment by jabrena** [comment]
http://www.crynwr.com/lego-robotics/
https://www.cs.duke.edu/courses/fall05/cps097s/cps004/notes/usinglejos.pdf
http://www.mralligator.com/rcx/opcodes.html
http://www.legoengineering.com/wp-content/uploads/2013/06/RCX-constructopedia-beta-1.0.pdf

**Comment by jabrena** [comment]
http://www.convict.lu/Jeunes/ultimate_stuff/Making%20your%20own%20RCX%20sensors_part2.pdf

**Comment by jabrena** [comment]
http://www.kovan.ceng.metu.edu.tr/mindstorms/

**Comment by jabrena** [comment]
https://pbrick.info/2013/10/configuring-the-lego-usb-tower-on-linux/

**Comment by jabrena** [comment]
http://www.technicopedia.com/index.html

**Comment by jabrena** [comment]
http://www.lejos.org/rcx/tutorial/getstarted/firstbrick/linux.html

**Comment by jabrena** [comment]
https://minordiscoveries.files.wordpress.com/2017/01/rpi_rcx.pdf

**Comment by jabrena** [comment]
```
robot@ev3dev:~$ ls -l /dev/usb/
total 0
crw-rw-rw- 1 root root 180, 160 Mar 19 20:35 legousbtower0
```

**Comment by jabrena** [comment]
```
sudo vi /etc/udev/rules.d/90-legotower.rules
ATTRS{idVendor}=="0694",ATTRS{idProduct}=="0001",MODE="0666",GROUP="robot"
```

**Comment by jabrena** [comment]
``` 
robot@ev3dev:~/rcx/lejos$ export LEJOS_HOME=/home/robot/rcx/lejos
robot@ev3dev:~/rcx/lejos$ export PATH=$PATH:$LEJOS_HOME/bin
robot@ev3dev:~/rcx/lejos$ export CLASSPATH=$CLASSPATH:.:$LEJOS_HOME/lib/classes.jar.:$LEJOS_HOME/lib/pcrcxcomm.jar
robot@ev3dev:~/rcx/lejos$ export RCXTTY=/dev/usb/legousbtower0
robot@ev3dev:~/rcx/lejos$ export JAVA_HOME=/usr/lib/jvm/java-9-openjdk-armhf
robot@ev3dev:~/rcx/lejos$  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LEJOS_HOME/bin
robot@ev3dev:~/rcx/lejos$ chmod +x /home/robot/rcx/lejos/bin/*
robot@ev3dev:~/rcx/lejos$ chmod +x /home/robot/rcx/lejos/release/*
```

**Comment by jabrena** [comment]
```
robot@ev3dev:~/rcx/lejos/bin$  ./firmdl
read firmware srec
  100%
Installing firmware
Loading native libs
Deleting firmware
Firmware deleted
Downloading firmware
  100%
Firmware downloaded
Unlocking firmware
Firmware unlocked
```

**Comment by jabrena** [comment]
robot@ev3dev:~/rcx/lejos/bin$ javac -bootclasspath "$LEJOS_HOME/lib/classes.jar:$LEJOS_HOME/lib/rcxcomm.jar" DistributionSmokeTest.java -target 1.6 -source 1.6

**Comment by jabrena** [comment]
```
robot@ev3dev:~/rcx/lejos/bin$ lejos DistributionSmokeTest
linking...
downloading...
read binary
  100%
download binary
Loading native libs
download program
  100%
  100%
```

**Comment by jabrena** [comment]
Running nice
