### ISSUE TITLE
Clean up builds from  build-scaleway-x64-ubuntu-16-04-2 

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#578]
It is necessary to review the server: `build-scaleway-x64-ubuntu-16-04-2` to clean old builds.

Comments from:  **martijnverburg**
```
FYI - Jenkins has been unable to clean up - 
build-scaleway-x64-ubuntu-16-04-2:/home/jenkins/workspace for ev3 builds
```

**Comment by JakubVanek** [comment]
I think that it might have something to do with the fact that we are building under the docker user and not under the jenkins one. We can try to run `rm -rf /build/*` in one of the containers.

**Comment by JakubVanek** [comment]
Perform manual workspace cleanup: https://github.com/ev3dev-lang-java/openjdk-ev3/commit/6abff5174fa3545052b5904e595ce4a26f1fe321

**Comment by JakubVanek** [comment]
Hmm, it didn't work yet - the command wasn't actually run in the containers.
Try 2: https://github.com/ev3dev-lang-java/openjdk-ev3/tree/cleanup

**Comment by JakubVanek** [comment]
Fixed, the problem was with using a variable that was declared in a non-parent scope.
