### ISSUE TITLE
Develop a simple IntelliJ plugin

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#582]
Template project is growing in the number of Gradle tasks about deployment processes. It is necessary to review if we could develop some kind of IntelliJ plugin for the project.

Many thanks @miguelcordovam

Related issue:
https://github.com/miguelcordovam/leJOS_plugin/issues/11

**Comment by robl0377** [comment]
Please don't forget us Eclipse users! 
With classic LeJOS I was happy to use their Eclipse Plugin. It would be great if ev3dev could provide one too.

**Comment by jabrena** [comment]
Hi @robl0377, 

Yes, but remember that it is a Open Source project we are collaborating in this project with our spare time. In 2018, you could see that Java developers choose IntelliJ as the main Java IDE. This is the reason to start with IntelliJ.

I paste some links:
https://www.improgrammer.net/10-best-java-ides-for-programmers/
https://www.slant.co/topics/607/~best-java-ides-or-editors

I propose something:
Why not participate in the project creating a Plugin for eclipse?
It could be nice, isn't it?

**Comment by robl0377** [comment]
Hmm, I'm an old hand with Eclipse, Java 6, ANT, and Subversion. Eclipse always was the best free Java IDE and until 2013 (in my last Java job) I used it professionally for application development.

Some hint from one of your links above about IntelliJ:
> David Poulet's Experience
It's not really a free IDE. The community edition is quite limited compared to Eclipse or even Netbeans. There are lots of plugins but many of them are not available in the free edition. If you spend the money though, the commercial very is probably the best IDE out there. 

So real Open Source developers should use a free IDE, don't you think? ;-)

About creating an Eclipse plugin myself: It would be quite a challenge and I don't know whether I could finish it. I think about it, though. No promises.

Actually, originally I wanted to port a program for a 2-wheel balancing robot for the Lego NXT controller from 2009, written in LeJOS NXT to some modern platform on the EV3 as a hobby. However, I'm still struggling with the development environment of ev3dev. 
So the first step of porting this program still is classic LeJOS EV3 v0.9.1beta for me: Eclipse & Plugin. Faster development turnaround time. Faster start time of the program on the brick (even with only 300MHz EV3 brick).

**Comment by JakubVanek** [comment]
I have created a repository at https://github.com/ev3dev-lang-java/intellij-plugin.

**Comment by jabrena** [comment]
@miguelcordovam, @robl0377, we have a new repo about the plugin. You are invited to participate!!!

Merry Christmas

**Comment by jabrena** [comment]
Related repository:
https://github.com/ev3dev-lang-java/intellij-plugin

**Comment by jabrena** [comment]
Reorganize the project
