### ISSUE TITLE
Document the Java installation through APT instead of installer.sh

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#589]
This issue is a continuation of https://github.com/ev3dev-lang-java/installer/issues/33 . We can either change the installer so that it only calls apt-get, or we can replace the installer altogether.

**Comment by jabrena** [comment]
Hi @JakubVanek, for EV3, we have a process opened to have Java in EV3Dev. It is not necessary to update that point. for Raspberry boards, this is current way.

**Comment by JakubVanek** [comment]
Installer now installs Java from APT.
