### ISSUE TITLE
Add a way to change the default user password

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#592]
Hi,

we use sudo in operations which need root access. Given that using the default password is a security risk, I think the password should not be hardcoded. Ideally, it should be taken from [config.gradle](https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/master/gradle/config.gradle)

Regards,
Jakub

**Comment by jabrena** [comment]
Totally agree with you @JakubVanek 

This is the reason, that the best way to evolve is the development of a IntelliJ plugin.
Meanwhile, we could improve the documentation and review how to read the credential from `config.gradle`.

Little by litte :)

**Comment by JakubVanek** [comment]
Delivered.
