### ISSUE TITLE
Implement communication with NXT

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#602]
http://www.lejos.org/nxt/nxj/tutorial/Preliminaries/GettingStartedLinux.htm
http://www.lejos.org/nxt/nxj/tutorial/PC_GUI/PCGUITools.htm
http://blog.electricbricks.com/2010/03/instalacion-de-lejos-en-linux/

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/pcsamples/
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/pccomms/
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/pctools/

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/pcsamples/src/org/lejos/pcsample/usbsend/USBSend.java

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/samples/src/org/lejos/sample/usbreceive/USBReceive.java

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/pcsamples/src/org/lejos/pcsample/remotepilotcontrol/RemotPilotTester.java

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/pcsamples/src/org/lejos/pcsample/socketserver/SocketServer.java

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/samples/src/org/lejos/sample/sockettest/SocketTest.java

**Comment by JakubVanek** [comment]
If you want to flash a firmware to NXT, I think you will have to use USB connection: http://www.lejos.org/nxt/nxj/tutorial/Preliminaries/GettingStartedLinux.htm
> Make sure your NXT is attached to the PC via USB cable and switch it on by pressing the orange button. Open a command line prompt and either type the command nxjflash or nxjflashg. The latter starts the GUI version of nxjflash.

This is because it uses the builtin Atmel SAM-BA uploading mechanism.

If you want to communicate with NXT over Bluetooth (or maybe even USB, I don't know), then yup, PC tools are the right way.

**Comment by JakubVanek** [comment]
http://www.lejos.org/nxt/nxj/tutorial/AdvancedTopics/UnderstandingFilesLCPMemTools.htm#4.1

**Comment by jabrena** [comment]
Yes, this is the idea.
With EV3Dev, you have full featured USB support, so anyone could interact with N NXT Bricks

**Comment by jabrena** [comment]
And my question is... Maybe why not use the same idea with other EV3?

**Comment by JakubVanek** [comment]
Hmmm, I have somehow mixed this with the bluetooth issue. Then yup, it makes sense.

What is your idea regarding the other EV3s?

**Comment by JakubVanek** [comment]
Hmmm, this feels similar to this issue: https://github.com/ev3dev/ev3dev-lang-python/issues/385 . It is not the same though.

Apparently NXT exposes itself on its gadget port as a kind of a smart serial port. EV3s expose themselves as Ethernet devices, so we can network them. This basically boils down to RMI or another RPC. One could then write a bridge between the RPC protocol and NXT.

**Comment by JakubVanek** [comment]
If one wanted just byte-oriented communication, the NXT socket proxy from the link above could be sufficient.

**Comment by jabrena** [comment]
Well, the idea is to establish communications with other useful Lego Mindstorms Bricks like NXT with LeJOS. This is something pending.

- EV3 - EV3 (With an USB Cable)
- EV3 - EV3 with LeJOS (With an USB Cable)
- EV3 - NXT with LeJOS (With an USB Cable)

**Comment by jabrena** [comment]
https://coderanch.com/mobile/t/274634/java/Java-listening-Serial-Port

**Comment by JakubVanek** [comment]
Hmmm:
* ev3dev - ev3dev
  * this can be configured in menu, however it is a bit limited
  1. configure the brick with cable plugged to the device port for tethering
  2. connect to the tethered brick on the one where the cable is in the host port
  3. now you should have a communication channel between two ev3dev ev3s
* ev3dev host port - lejos ev3 device port
  * lejos emulates ethernet device too, so it should be only necessary to connect to it from ev3dev
  * lejos uses a bit different IP ranges
* lejos ev3 host port - ev3dev device port
  * here it will be necessary to enable tethering on the ev3dev brick
  * lejos should somehow detect the brick as a new ethernet device, I don't know if it works
* lejos ev3 - lejos ev3
  * I have no idea if that works, but theoretically it could as well

I'm thinking that some daisy-chain messaging daemon running on the bricks could be used to break through the individual ethernet address spaces. I don't know if using Java is a good idea - it may be slow, but it would work on leJOS without problems.

Adding NXT to this:
* NXT device - any host
  * it will be necessary to reimplement/use the communication protocol of leJOS NXJ PC Comms to implement an ethernet and messaging proxy

However, I'm not sure if all this is necessary: https://lejosnews.wordpress.com/2015/02/27/pan-the-lejos-answer-to-daisy-chaining/, and here even wifi can be used.

Jakub

**Comment by JakubVanek** [comment]
NXT cannot use bluetooth networking or wifi, so there the issue is real.

**Comment by jabrena** [comment]
It is very easy to connect 2 bricks or more.

![](http://www.erichuang.com/uploads/1/4/8/2/14828090/805285458.png)

```
Linux ev3dev 4.14.80-ev3dev-2.3.1-ev3 #1 PREEMPT Tue Nov 13 13:08:11 CST 2018 armv5tejl
             _____     _
   _____   _|___ /  __| | _____   __
  / _ \ \ / / |_ \ / _` |/ _ \ \ / /
 |  __/\ V / ___) | (_| |  __/\ V /
  \___| \_/ |____/ \__,_|\___| \_/

Debian stretch on LEGO MINDSTORMS EV3!
Last login: Sun Dec  2 15:22:38 2018 from 192.168.2.1
robot@ev3dev:~$ clear

robot@ev3dev:~$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-ev3)
OpenJDK Client VM (build 11.0.1+13-ev3, mixed mode, sharing)
robot@ev3dev:~$ lsusb
Bus 001 Device 003: ID 0bda:8152 Realtek Semiconductor Corp. 
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
robot@ev3dev:~$ lsusb
Bus 001 Device 003: ID 0bda:8152 Realtek Semiconductor Corp. 
Bus 001 Device 004: ID 0694:0005 Lego Group 
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
robot@ev3dev:~$ ping 169.254.204.13
PING 169.254.204.13 (169.254.204.13) 56(84) bytes of data.
64 bytes from 169.254.204.13: icmp_seq=1 ttl=64 time=4.53 ms
64 bytes from 169.254.204.13: icmp_seq=2 ttl=64 time=1.86 ms
64 bytes from 169.254.204.13: icmp_seq=3 ttl=64 time=1.83 ms
^C
--- 169.254.204.13 ping statistics ---
19 packets transmitted, 19 received, 0% packet loss, time 18030ms
rtt min/avg/max/mdev = 1.290/2.022/4.532/0.651 ms
robot@ev3dev:~$ ssh robot@169.254.204.13
The authenticity of host '169.254.204.13 (169.254.204.13)' can't be established.
ECDSA key fingerprint is SHA256:sNNNlUWTtDtWX0CbCLcC83h8Yohuql2x2f6elfXKf+c.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '169.254.204.13' (ECDSA) to the list of known hosts.
Password: 
Linux ev3dev 4.14.80-ev3dev-2.3.1-ev3 #1 PREEMPT Tue Nov 13 13:08:11 CST 2018 armv5tejl
             _____     _
   _____   _|___ /  __| | _____   __
  / _ \ \ / / |_ \ / _` |/ _ \ \ / /
 |  __/\ V / ___) | (_| |  __/\ V /
  \___| \_/ |____/ \__,_|\___| \_/

Debian stretch on LEGO MINDSTORMS EV3!
robot@ev3dev:~$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-ev3)
OpenJDK Client VM (build 11.0.1+13-ev3, mixed mode, sharing)
robot@ev3dev:~$ 
```

**Comment by jabrena** [comment]
```
sudo apt-get install libusb-0.1-4
```

**Comment by jabrena** [comment]
Rejected by LEAN
