### ISSUE TITLE
Unify gradle tasks in the whole project

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#606]
Hi,

there are now two build systems - ones using the old gradle structure and then template-project-gradle. I think the systems should be merged to just one (i.e. add to template-project what is not in the rest and then replace the old systems with the new one). We could remove some features for the other projects, like ev3dev commands, if that would cause bloat.

Regards,

Jakub

- [x]  [EV3Dev-lang-java](https://github.com/ev3dev-lang-java/ev3dev-lang-java): Low level interation with EV3Dev
  - PR https://github.com/ev3dev-lang-java/ev3dev-lang-java/pull/646 is merged
- [x]  [Template project](https://github.com/ev3dev-lang-java/template_project_gradle): A Gradle project ready to test the project
  - the plugin was built with this project as a model
  - PR https://github.com/ev3dev-lang-java/template-project-gradle/pull/28 is merged
- [x]  [Examples](https://github.com/ev3dev-lang-java/examples): A repository with several examples about the usage of this project
  - PR https://github.com/ev3dev-lang-java/examples/pull/2 is merged

**Comment by jabrena** [comment]
Yes, we will do, but not immediately. it is not blocking for the development and the community.

Now, I am trying to stabilize `examples project` which it has a multi module structure to run better with Lombok support. Later, add new gradle files in the different modules is trivial. We will do.

**Comment by jabrena** [comment]
Next week, I will unify in a gradual way.

**Comment by JakubVanek** [comment]
Hmmm, it seems that the only extra thing is the docker build for the main project. This can remain where it is now.

**Comment by JakubVanek** [comment]
I think the docker-supporting gradle code could be removed:
http://paulbakker.io/java/docker-gradle-multistage/

**Comment by jabrena** [comment]
Yes, we will do, the Gradle plugin to manage docker is Palantir.
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/424

In some moment, we will upgrade that part.

**Comment by JakubVanek** [comment]
Oki, I was thinking that Gradle could be bypassed and that the Dockerfile would handle everything by itself.

**Comment by jabrena** [comment]
I have to test how to publish the gradle plugin in Jitpack before integrate the gradle plugin into the template project and later in the rest of Gradle projects.
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/632

I will test in the following days

**Comment by JakubVanek** [comment]
I achieved it for the current gradle plugin this way:
1. I tagged a commit on master and downloaded it from jitpack,
2. I added jitpack repository to build.gradle,
3. I added the plugin classpath to build.gradle.

**Comment by JakubVanek** [comment]
The three stable projects are finished now. I have quickly looked through the repositories in this project and it seems that these have their custom deployment code too:

 * https://github.com/ev3dev-lang-java/RPLidar4J
 * https://github.com/ev3dev-lang-java/usb-devices
 * https://github.com/ev3dev-lang-java/lejos-navigation

However I think that we can finish these in the next iteration.

**Comment by JakubVanek** [comment]
Hmmmm, I have realized something - you should now be able to deploy a program on vanilla EV3 ev3dev directly from the template project.
```sh
./gradlew uploadGradleLibraries
./gradlew deploy
```

Java is already preinstalled on EV3 and the library-upload step effectively replaces the `installJavaLibraries` task (but it doesn't have to). You only have to launch installer when you want to use OpenCV or RXTX.

There might be an issue with creating the base `/home/robot/java` directory, because SFTP mkdir is not recursive and so it would be needed to be created first. That could be fixed easily.

**Comment by JakubVanek** [comment]
Hmmm, on the other hand the installer setup on EV3 is not complicated or time consuming, so there is not that much benefit.
```sh
./gradlew getInstaller installJavaLibraries
```
