### ISSUE TITLE
Add the method drawOval in the interface GraphicsLCD

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#608]
I will add the support for the new method `drawOval` in the different parts:

- [x] Create `adr-lejos` to track change in the interface
- [x] lejos-commons (Interface GraphicsLCD)
- [x] ev3dev-lang-java (LCDStretch & LCD Jessie)
- [x] enable the example in template: https://www.youtube.com/watch?v=iD5OcfiN3f0

``` java
    public void drawOval(int x, int y, int width, int height) {
        g2d.drawOval(x, y, width, height);
    }
```

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/580

**Comment by JakubVanek** [comment]
#607 should be addressed after this.

**Comment by jabrena** [comment]
Released Snapshot:
https://jitpack.io/#ev3dev-lang-java/ev3dev-lang-java/2.5.2-SNAPSHOT

**Comment by jabrena** [comment]
https://jitpack.io/#ev3dev-lang-java/ev3dev-lang-java/2.5.3

**Comment by jabrena** [comment]
Added
