### ISSUE TITLE
Create test support for Installer project running on Travis

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#618]

**Comment by JakubVanek** [comment]
https://github.com/JakubVanek/elj-install/tree/travis

**Comment by JakubVanek** [comment]
https://travis-ci.org/JakubVanek/elj-install

**Comment by jabrena** [comment]
Oki, when you feel happy with the tests, we could create a PR to merge in the repo.
This set of tests will be very useful for the future.

**Comment by jabrena** [comment]
Related PR:
https://github.com/ev3dev-lang-java/installer/pull/40/files#diff-63ab6decfd52638355f6a527c3c6dee2R24

**Comment by jabrena** [comment]
https://travis-ci.org/ev3dev-lang-java/installer/builds/465727367

**Comment by jabrena** [comment]
Fixed
