### ISSUE TITLE
Develop a library to build User Interfaces for EV3 Display

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#620]
Some applications require a User Interface to interact with the user.

**Comment by JakubVanek** [comment]
We could base it on my old library and configuration tool:
https://gitlab.com/robovanek/robo2015-ss/tree/master/program/microgui
https://gitlab.com/robovanek/robo2015-ss/tree/master/program/cfgtool

**Comment by JakubVanek** [comment]
I recommend trying it out on real leJOS EV3. However, it works also on the desktop via Swing.

**Comment by JakubVanek** [comment]
It may need some reachitecting, I remember regretting some design decisions later (like the way that user has to write the UI screens).

**Comment by jabrena** [comment]
Well, the idea is to develop some kind of Util classes to build and interface combining Buttons and the display. It is an incubator project in this stage.

**Comment by jabrena** [comment]
Rejected by LEAN
