### ISSUE TITLE
Maintenance question

### ISSUE THREAD

**Issue by bjost2s** [ev3dev-lang-java/ev3dev-lang-java#638]
In this readme you have this note "At the moment, we will maintain the whole solution until the next LEGO Mindstorms product estimated for next January of 2020."
How reliable is this date and do you have a plan for the next LEGO Mindstorms product?
I came across this project because we have already a full working implementation of lejos in the Open Roberta Lab and we also support ev3dev, but with Python.
Thank you very much.

**Comment by jabrena** [comment]
Good morning @bjost2s,

as @JakubVanek commented, it is a forecast. 

In relation to your question:

> do you have a plan for the next LEGO Mindstorms product?

**The answer is Yes.** The most important thing is the creation of a diverse, multidisciplinary community/team. In my case, I start contributing LeJOS ecosystem 10 years ago with the creation of current website, https://www.lejos.org and the development of diverse drivers like the GPS support, NXTCam, Lattebox and others devices. Some years ago, I observed the evolution of LeJOS project and the potential of EV3Dev and I decided to port the project to a complete Distro. For the next generation if the concept about EV3Dev survive, I will continue developing and helping the community in other case, I will have to see how to continue running Java on Mindstorms Bricks, but I will continue here. With the time you learn that every hour with a Brick is a Knowledge investment in the stack that you like (Java, Linux, etc...) :)

In relation to the integration of `Open Roberta Lab` with `LeJOS` or `EV3Dev with Python`, it is cool. This year, I will develop a Cloud compiler for EV3 but in general it will compatible with any JVM.

LeJOS project or Java for EV3Dev (this project) try to help the community with the idea to learn some technologies using the vehicle of a Brick. In this case, any user will learn many stuff about Java, Linux, Robotics, LeJOS APIs, Communications... It is a live project contributing and learn.

Tell me if you have any additional question.

Cheers

Juan Antonio
