### ISSUE TITLE
Define goals for 2019

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#643]
For this year, it is necessary to review:

- Backlog
- Open pull requests

With that information, it is necessary to reschedule milestones for 2019 in order to put priorities.

-[ ] USB Device Support
-[ ] ROS Support
-[ ] Improve communication activities
-[ ] Initial Remote Support
-[ ] NXT Support

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/413

**Comment by jabrena** [comment]
Any suggestion for this Year?

@chgandm, @jaakkos, @jeperez, @jweijers, @MartinKvicala, @Mayt38, @DMyTryC, @mominbilal, @nmatra, @Quingu, @submars, @jartu, @mingan666

**Comment by jartu** [comment]
One two cents: My impression is that it's still relatively difficult for a newcomer to set everything up correctly (perhaps both on the brick and also on the Mac/PC) and start developing. I would vote for improving the documentation.

BTW: What's the relationship between the ev3dev-lang-java team and the ev3dev.org organization as a whole? Are we completely independent?

Thanks, J.

**Comment by jabrena** [comment]
Hi Jartu,

> BTW: What's the relationship between the ev3dev-lang-java team and the ev3dev.org organization as a whole? Are we completely independent?

In relation to the grade of teamwork, both projects are independents. They provide a Debian build for EV3 and Raspi boards and we provide the Java implementation with the LeJOS flavor but we operate in an independent way. @dlech is the lead maintainer of EV3Dev. From the last Snapshot of EV3Dev, Java installed by default, this is the last collaboration and a patch in a debian package required for OpenCV installation.

**Comment by jabrena** [comment]
> One two cents: My impression is that it's still relatively difficult for a newcomer to set everything up correctly (perhaps both on the brick and also on the Mac/PC) and start developing. I would vote for improving the documentation.

Yes, we need to improve in documentation.

In this direction, In January, I want to release the new website:
https://ev3dev-lang-java.github.io/ux/

Juan Antonio

**Comment by jabrena** [comment]
Besides, we should tinker with Kotlin too...

**Comment by jabrena** [comment]
Added, the last LeJOS Developers:  @gloomyandy @Asw1n in the loop.

**Comment by jartu** [comment]
The https://ev3dev-lang-java.github.io/ux/ site would be a great help for users. Great idea!
J.

**Comment by jabrena** [comment]
An initial release will be deployed this week. In the next release, we will add a section about articles. Last year, we did many technical progress and it is necessary to explain in articles.

Take a look this repo:
https://github.com/lucilejerber/ATVisep/blob/master/src/main/java/example/Motor.java

``` Java
public static void multiplicationMatrice(float forces[][], float direction[], float valeursInterMoteurs[], int valeursMoteurs[])
    {
        valeursMoteurs[0] = 0;
        valeursMoteurs[1] = 0;
        valeursMoteurs[2] = 0;
        valeursInterMoteurs[0] = 0;
        valeursInterMoteurs[1] = 0;
        valeursInterMoteurs[2] = 0;
        for(int i = 0; i < 3; i++)
        {
            for (int j = 0; j < 3; j++)
            {
                valeursInterMoteurs[i] = valeursInterMoteurs[i] + forces[i][j] * direction[j];
            }
        }
        for(int i = 0; i < 3; i++)
        {
            valeursMoteurs[i] = (int)(valeursInterMoteurs[i] * 100);
        }
    }

```

**Comment by jabrena** [comment]
In my case, this year I will put the focus on: ROS support, The cloud EV3 Compiler & EV3 Docking station

**Comment by mingan666** [comment]
Unfortunately, I do not have much time for my mindstorms project. Therefore, I will only contribute to this project if there is something I need for my my robot.

However, I do have some issues with the gradle structure in the template project so I will try to contribute within that area. Mainly I would like to make it easier to work against not yet released dependencies.

**Comment by JakubVanek** [comment]
Hi @mingan666,

there is a 'plugined' branch in template project - that is hopefully going to be merged to master. Plugin now handles ev3dev-specific actions.

Dependencies relate to template project in three ways (in the new slim jar mode):
* Installation of our libraries. This is done by [installer.sh](https://github.com/ev3dev-lang-java/installer). It installs a predefined set of libraries to `/home/robot/java/libraries`. This is not meant for user-made changes. Hmm, @jabrena we must keep versions between template and installer in sync.
* Gradle library inclusion. Users can specify their own libraries in the dependencies block in build.gradle. The plugin code then adds `/home/robot/java/libraries/<jarname>.jar` to the classpath. The JAR doesn't have to be there, it can be also added through `brick.pref.libCustom` list in config.gradle.
* User defined uploads. The library JAR can be uploaded alongside the program. It is just necessary to override the `brick.build.uploads` lambda to return a list in form of `[java.nio.file.Path of source file, String with on-brick destination path, Integer with destination Unix file mode]`.

Regards,

Jakub

**Comment by JakubVanek** [comment]
You can also change the version of this project's libraries in build.gradle, but you then have to put it on the brick through the ways outlined above.

**Comment by JakubVanek** [comment]
You also do not have to use `brick.build.uploads`, you can just install it through SSH or directly on the SD card.

**Comment by JakubVanek** [comment]
You should also be able to use non-Maven dependencies in Gradle through using the `files()` directive: https://stackoverflow.com/a/20956456

**Comment by mingan666** [comment]
Ok, looks need. What time frame do you see for merging?

However, I don't like the installer script for dependency installation, since the dependencies are hard coded. My idea is to try fix something similar to maven copy-dependencies. Then all dependencies will be available within a directory of the project and it should be simple to update the plugin to copy all files in that directory to /home/robot/java/libraries.

That would mean that the dependency install would fix the correct versions of the used dependencies according to the actual project. It should be easier to keep it in sync compared to hard coded paths in a installer script.

I'm used to maven instead of gradle, but I plan to look into this for myself. If I get a working solution for coping the dependencies, I can let you know.

**Comment by mingan666** [comment]
Could not really find how the brick.build.uploads would look like, but it seems it will still need to have specified the correct versions. It seems like it would need the complete source file name, which for example for a locally compiled ev3dev-lang-java would look like this: 
`/home/xxxx/.m2/repository/com/github/ev3dev-lang-java/ev3dev-lang-java/2.5.4/ev3dev-lang-java-2.5.4.jar`

My thought here is that this should not be necessary... the information is already available within gradle and I just want to make use of that :)

**Comment by mingan666** [comment]
Ok, it wasn't hard at all to gather the dependencies. Code snippet from my projects build.gradle:

```
dependencies {
    compile("org.slf4j:slf4j-simple:1.7.25")
    compile("com.github.ev3dev-lang-java:ev3dev-lang-java:2.5.4")
}
task copyDependencies(type: Copy) {
    from configurations.compile
    into 'dependencies'
}
```
Then running the new task will copy the dependencies nicely to the project structure:
```
$ ls dependencies/
ev3dev-lang-java-2.5.4.jar  jna-4.5.2.jar  lejos-commons-0.7.3.jar  slf4j-api-1.7.25.jar  slf4j-simple-1.7.25.jar
```

So, it would be great if the new plugin could have a task to copy all files within that subdirectory to the appropriate directory on the brick.

**Comment by JakubVanek** [comment]
Regarding the upload block, this should work:
```gradle
brick.build {
    uploads = { proj ->
        return [
            [Paths.get(proj.projectDir.getAbsolutePath(), "mysterious_data_file.bin"), "/home/robot/mysterious_data_file.bin", 0755],
        ]
    }
}
```

It is a lambda, so you could iterate over the libraries and filter the one you want to upload. 

The idea to iterate over libraries to install them from the gradle project was once implemented, but it was rejected because it made the template-project-gradle code responsible for installing the base environment. @jabrena https://github.com/ev3dev-lang-java/template-project-gradle/blob/8bc94b87ecf88e8528e5aab5d16d4cfd60ea766c/gradle/installer.gradle#L63

The idea to copy the dependencies to a directory looks good to me - it adds flexibility to the project. I think this doesn't have to go to the plugin, this can be directly added to build.gradle.

Regards,

Jakub

**Comment by JakubVanek** [comment]
Edit: you have to use `import java.nio.file.Paths` in the upload config. Updated inline.

**Comment by JakubVanek** [comment]
More config.gradle options can be found here: https://github.com/ev3dev-lang-java/template-project-gradle/pull/28#issuecomment-450669484

**Comment by mingan666** [comment]
How do you figure? 

> because it made the template-project-gradle code responsible for installing the base environment

I don't see this being part of the base environment, instead I see this as being part of installing the actual project. It will not run without the appropriate jar files being present. Changing a version within the gradle.build makes me jump to all sorts of hops (updating installer file, or worse manually transferring the files)...

One option might be to add the possibility to transfer at least the ev3dev-lang-java from that project instead. The installer file could not copy the correct version for me, since it was not available on jitpack...

**Comment by mingan666** [comment]
Regarding another issues: What is the meaning of openjdk11 support? Is it only runtime support?

From the build.gradle:
```
compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}
```

When I was testing openjdk11 on windows and linux I run into issues with the gradle version.

Maybe an idea to update to openjdk 11 and gradle 5?

**Comment by JakubVanek** [comment]
Hmmm, when I'm thinking about it, originally the idea was to have wget code in Gradle, not in installer:
https://github.com/ev3dev-lang-java/template-project-gradle/commit/14f2c4305dfb1a717eb031e867bf50447dbcfeb0

The idea probably was that the base environment is independent from the plugin (i.e. maven could be used in future as well). It also came from history -- originally everything was installed manually by installer.sh and libraries were packaged inside the program JAR. Installer is now integrated in Gradle and libraries are by default separate (but you can use `brick.pref.smallJar = false` to package everything inside the program file). We can change the behavior if we discuss it.

**Comment by mingan666** [comment]
But I liked the changes to the small jar :)

For me its actually not a big issue. I'm capable of doing the needed changes for my own build. 

I just think it will be easier for beginners that add additional libraries. Also it eliminates one of the sync issues between the different projects as well as it makes it easier when bug fixing issues within ev3dev-lang-java - make some changes locally and get them easily transferred to brick.

However, installer would still be valid for jdk and stuff. (if you'r not like me and prefer that manually :)

**Comment by JakubVanek** [comment]
Hmmm, not all platforms are running OpenJDK 11: [Debian jessie on non-EV3 platforms runs JDK 8](https://github.com/ev3dev-lang-java/installer/blob/abda5780a05a569085f2e46f051d2130707fc433/installer-jessie.sh#L30)

**Comment by mingan666** [comment]
Have you actually used openjdk11 to build the project with gradle 4.7? Because that doesn't work for me. I'm not sure gradle 4.x is compatible with jdk11?

What kind of issues did you run into? In windows/ubuntu I'm cmd-line I'm able to compile ev3dev-lang-java with the following versions:
```
------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-Ubuntu-3ubuntu118.04ppa1)
OS:           Linux 4.4.0-17134-Microsoft amd64
```

**Comment by JakubVanek** [comment]
No, I haven't actually tried compiling the code. Gradle 4.11 (or 5.0) should be compatible in that case.

Could you try running the program through gradle on the brick? https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/529#issuecomment-433742521 indicates that the problem lies there. `deployAndRun` task should test it.

Thanks,

Jakub

**Comment by mingan666** [comment]
Works at least fine in the template project with my code.

**Comment by JakubVanek** [comment]
Oki, that is strange. If it works, then there should be no technical problem in switching to OpenJDK 11 and Gradle 5.0 for building (separately from Java 1.8 targetting).

I'm not sure about the `-Xshare:on` problem. This may indicate that the [CDS archive creation](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/ca1adc6e15a60ef549dbc3e1cfe00d562e27baaf/packaging/debian/postinst.in#L61) failed. What does it print? However I think it would be good to create a new issue to not make this thread extra long.

Thanks,

Jakub

**Comment by JakubVanek** [comment]
Hi,

Juan messaged me that he will review and merge the plugin tomorrow.

Regards,

Jakub

**Comment by jabrena** [comment]
Mates, in relation to the plugin, it was merged and the idea from @mingan666 too. 

We need to return to the conversation about the Goals for 2019. The template project is an engineering tool to help in the development, but we need to put the focus on Robotics features this year.

@mingan666 I have curiosity in your robot project. What is the purpose?

**Comment by JakubVanek** [comment]
There are two new tasks:
* upgrade to Gradle 5 and OpenJDK 11 for building,
* decide if library JARs should be uploaded from user projects. If we settle for yes, we should decide which libraries should be removed from this (like OpenCV from Debian).

**Comment by jabrena** [comment]
Hi Jakub, can you create a issue properly?
This issue is not the place.

**Comment by JakubVanek** [comment]
I think that investigating the usage of libudev and reworking the device backend might be interesting.

**Comment by jabrena** [comment]
Hi Jakub, 

the topic about libudev could be interesting but I will delay until the project evolve in other areas like:

-[ ] Bluetooth Support
-[ ] USB Device Support
-[ ] ROS Support
-[ ] Initial Remote Support

Last year, we invested so much time to evolve the core library to Debian Stretch and now, the library is stable, so it is not necessary to touch that part. It is more important to evolve other new areas.

**Comment by mingan666** [comment]
@jabrena: the purpose of my project is having fun :)

As mentioned previously I do not have that much time to spend with this, so I'll have to see if anything happens in the near future. Last time I had some time it all went into trying to get stuff working with openjdk 11 - as mentioned before, it isn't really working...

I've been working on a rubic's cube solver, but I'm really sure I'll continue with it. To many issues and to little time...

**Comment by jabrena** [comment]
Everyone are in the project for fun :)

> I've been working on a rubic's cube solver, but I'm really sure I'll continue with it. To many issues and to little time...

**Super WOW!**
That project could be an excellent example for the project!
Tell me if you need some kind of support or help.

All OpenCV activities are running in BrickPi or in a Smartphone?
