### ISSUE TITLE
Upgrade Java and Gradle for build

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#644]
We should upgrade the build code to use Gradle 5 and allow the use of Java 11.

**Comment by jabrena** [comment]
It is a good idea.
We should apply for the library and template project.
Can you send a PR for it?

**Comment by JakubVanek** [comment]
Plugin PR: https://github.com/ev3dev-lang-java/gradle-plugin/pull/12 (merged)
Library PR: https://github.com/ev3dev-lang-java/ev3dev-lang-java/pull/679
Examples PR: https://github.com/ev3dev-lang-java/examples/pull/5
Template project PR: https://github.com/ev3dev-lang-java/template-project-gradle/pull/35

**Comment by JakubVanek** [comment]
Reassigning to reflect pending reviews

**Comment by jabrena** [comment]
Fixed
