### ISSUE TITLE
Upload most library JAR files from user projects

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#645]
This should make it easier for users to add new dependencies or change their versions. https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/643#issuecomment-453156103

There is an overlap with https://github.com/ev3dev-lang-java/template-project-gradle/pull/30. We can stop there and let the user upload the libraries manually.

**Comment by JakubVanek** [comment]
Hmmm, for user libraries, a `deployLibrary` task might be useful - it would install the compiled JAR to the directory for libraries.

**Comment by jabrena** [comment]
I agree with you @JakubVanek, but we need to priorize.

We have 10 main repos and we need to upgrade some incubator projects to promote as stable. This is the main reason.
https://ev3dev-lang-java.github.io/ux/projects.html

**Comment by jabrena** [comment]
In that case, is it resolved?

**Comment by JakubVanek** [comment]
It depends. The original intent of this issue is to reintroduce https://github.com/ev3dev-lang-java/template-project-gradle/blob/8bc94b87ecf88e8528e5aab5d16d4cfd60ea766c/gradle/installer.gradle#L63 and potentially remove java library installation from `installer.sh`. Alternatively, if we decide that https://github.com/ev3dev-lang-java/template-project-gradle/pull/30 is enough, we can close it.

I think that it would be useful to copy libraries from Gradle.

I think that providing both ways would be the best option. People who do not use Gradle would have a basic environment present, while people who use additional libraries in their Gradle projects could upload them from Gradle easily.

**Comment by JakubVanek** [comment]
Hi @mingan666, @jabrena,

I have hopefully added the needed functionality. If you run the `uploadGradleLibraries` task on the latest template project, it will upload the necessary JARs to the brick. To add a custom library, just add the dependency to the `compile` or `runtime` group.

However default libraries still are installed in installer.sh as well, so nothing should be broken.

I think this issue can be closed now.

Regards,

Jakub

**Comment by JakubVanek** [comment]
The new upload code is used in the Examples: [README.md#Checking it out](https://github.com/ev3dev-lang-java/examples/blob/1c38a6368dd7c7b7eab8c68e7c18a46ac347d4a0/README.md#checking-it-out).
