### ISSUE TITLE
Brake, coast, float etc. probably do not work

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/ev3dev-lang-java#665]
Hi,

the functions in `BaseRegulatedMotor` which operate on `STOP_COMMAND` probably do not operate as intended. They only set what should be done once `stop()` is called. However this is not consistent with the behavior on lejOS, where `flt()` actually performs the release of the motor pins.

Regards,

Jakub

**Comment by jabrena** [comment]
Hi @JakubVanek, all stop modes is working. In LeJOS only exist flt() but the most closed behaviour in EV3Dev is coast.

**Comment by JakubVanek** [comment]
Hi, the issue I see is not that `float` mode does not exist. The issue is that the specified action is executed only once stop() is called. This is changed in the #667 PR, which adds a common `doStop()` function.
