### ISSUE TITLE
Use TemplateProject with Java 13 and Gradle

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#675]
In order to use latest features from Java, it is necessary to upgrade Template Project to work with:

- Java 13
- Latest Gradle: https://github.com/gradle/gradle/issues/8681
- Review plugins in order to be compatible.

**Comment by JakubVanek** [comment]
Plugin PR: https://github.com/ev3dev-lang-java/gradle-plugin/pull/12 (merged)
Library PR: https://github.com/ev3dev-lang-java/ev3dev-lang-java/pull/679
Examples PR: https://github.com/ev3dev-lang-java/examples/pull/5
Template project PR: https://github.com/ev3dev-lang-java/template-project-gradle/pull/35

**Comment by JakubVanek** [comment]
EDIT: no PRs yet; my removed comment linked PRs for the Java 11 move.

**Comment by jabrena** [comment]
I am going to close this one, with Java 11, is enough.
