### ISSUE TITLE
Detect Buster Distro

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#700]
It is necessary to add support for EV3Dev Buster
https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2019-10-23/
https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2019-10-23/snapshot-ev3dev-buster-ev3-generic-2019-10-23.img.xz

**Comment by JakubVanek** [comment]
I already had to implement this in the integrated setup for gradle-plugin:

https://github.com/ev3dev-lang-java/gradle-plugin/blob/d61763b8bf8ab422012dfbcd2390f21c765a5df3/src/main/resources/setup.sh#L43-L47

**Comment by JakubVanek** [comment]
Related to this: https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/616

**Comment by jabrena** [comment]
Lack of time
