### ISSUE TITLE
Checkstyle violations while build

### ISSUE THREAD

**Issue by snuyanzin** [ev3dev-lang-java/ev3dev-lang-java#705]
First of all thank you for this project!

While building I noticed more than 50 checkstyle violations like 
```
Checkstyle rule violations were found. See the report at: file:///home/serg/code/projects/ev3dev-lang-java/build/reports/checkstyle/test.html
Checkstyle files with violations: 56
Checkstyle violations by severity: [warning:3271]

```

They are not hard to fix from my point of view however it is still unclear for me if the current checkstyle is actual at `config/checkstyle/checkstyle.xml`

**Comment by jabrena** [comment]
Hi @snuyanzin,

I added the plugin but the migration was paused.
I will continue with the `Checkstyle` support this year.

Juan Antonio
