### ISSUE TITLE
Remove Gradle plugin from template repository

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#717]
https://github.com/ev3dev-lang-java/examples

- [x] Identify git commit to review changes to restore previous Groovy scripts
- [x] Revert changes in the base code
- [x] E2E Test

Related issue: https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/714

**Comment by JakubVanek** [comment]
I don't think the plugin was ever deployed in these repositories:
https://github.com/ev3dev-lang-java/lejos-commons/blob/master/build.gradle
https://github.com/ev3dev-lang-java/lejos-navigation/blob/master/build.gradle

**Comment by jabrena** [comment]
Commit: `ed39b7f`

**Comment by jabrena** [comment]
Fixed
