### ISSUE TITLE
Test last builds from AdoptOpenjdk CI

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#719]
https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/

**Comment by JakubVanek** [comment]
Fix for JDK11 build: https://github.com/ev3dev-lang-java/openjdk-ev3/pull/53

**Comment by JakubVanek** [comment]
JDK15 build fixes: https://github.com/ev3dev-lang-java/openjdk-ev3/pull/54
JDK14 changes (docs only): https://github.com/ev3dev-lang-java/openjdk-ev3/pull/55

**Comment by jabrena** [comment]
When you have all builds in Green, design a Strategy to add tests from:
https://github.com/AdoptOpenJDK/openjdk-tests

In OpenJDK 10, I did in a semi manual way. With Native hardware, we should pass the tests.

**Comment by JakubVanek** [comment]
> When you have all builds in Green, design a Strategy to add tests from:
> https://github.com/AdoptOpenJDK/openjdk-tests

I have left the AdoptOpenJDK GitHub org, so I don't have permissions on Jenkins and we will have to wait for next scheduled rebuild (13.4. for JDK11, 11.4. for JDK15).

**Comment by JakubVanek** [comment]
> When you have all builds in Green, design a Strategy to add tests from:
> https://github.com/AdoptOpenJDK/openjdk-tests

Also please don't count on me doing this soon, if you want to do a new release in near future, please move it to the next milestone.

**Comment by jabrena** [comment]
I will use this issue to review the builds in this period, May-June 2020 but I will create a new issue to add OpenJDK test without any time pressure. :)

**Comment by jabrena** [comment]
Lack of time
