### ISSUE TITLE
Build Debian package from Jenkins for OpenJDK for EV3

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#729]
It is necessary to enable the process in Jenkins to  generate the Debian package for EV3DEV.

Assigned to: @JakubVanek

**Comment by JakubVanek** [comment]
First build with debian packages succeded:
https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/buster-bleeding/42/
