### ISSUE TITLE
Review AdoptOpenJDK Status to fix issues

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#742]
It is necessary review AdoptOpenJDK view to fix the issues:
https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/

![image](https://user-images.githubusercontent.com/147263/100428503-54be9000-3094-11eb-9bc4-1b014aa9586c.png)

**Comment by jabrena** [comment]
Running Pipelines for Java 11
https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/stretch-11/
https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/buster-11/

**Comment by jabrena** [comment]
Both pipelines fails.
Did you test in local @JakubVanek ?

```
checking for cacerts file... fail
configure: error: Specified cacerts file "/build/openjdk-build/security/cacerts" does not exist
configure exiting with result code 1
```

**Comment by JakubVanek** [comment]
@jabrena this is a known issue, please see https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/746.

**Comment by JakubVanek** [comment]
* JDK11 build (buster) is OK now: https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/buster-11/66/
* JDK12 build should succeed, last failure was likely only due to https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/746
* JDK13 build will fail due to out-of-date patches
* JDK14 build should succeed, even the last build was successful
* JDK15 build does not exist yet
* JDK master will fail due to out-of-date patches

**Comment by JakubVanek** [comment]
JDK13 fix: https://github.com/ev3dev-lang-java/openjdk-ev3/pull/76
JDK master/tip fix: https://github.com/ev3dev-lang-java/openjdk-ev3/pull/77

**Comment by JakubVanek** [comment]
@jabrena The Buster JDKmaster build has locked up: [Buster JDKMaster#71](https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/buster-bleeding/71/). The JDK build step normally takes around 13 minutes (including a bootcycle build). For current build it already took 45 minutes.

I don't know how to debug this. It might be that the pass 1 JDKmaster build has crashed while compiling pass 2 JDKmaster (this is what gets distributed). 

This is one of the reasons I don't want to touch this anymore  and why I would very much prefer not building custom JVMs.

**Comment by JakubVanek** [comment]
What's more, as the builds are not able to exit themselves, they block the `docker-packet-ubuntu1604-armv8-1` executor (the only one that satisfies the current requirements) until someone terminates them manually. In the meantime other AdoptOpenJDK jobs don't get a chance to run on that executor (I remember that there is some docker job that gets blocked).

**Comment by JakubVanek** [comment]
Even the restarted build froze: https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/buster-bleeding/72/console
I'd give it a few more minutes to see if this isn't just a particularly difficult part of the build, but it doesn't seem so.

**Comment by jabrena** [comment]
Currently, everything is in order
