### ISSUE TITLE
Add Support for Java 15 on AdoptOpenJDK

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#744]

**Comment by JakubVanek** [comment]
@jabrena Would it be possible to rename the jobs to follow the current convention? The build system does not like the space in the job name: https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/Buster%20JDK15/1/console The jobs will need to be created anew and named ideally as buster-15 and stretch-15 (current convention). In extended job configuration there should be another field called Display Name and this is where "Buster JDK15" should go.

**Comment by JakubVanek** [comment]
PR with which we should be able to remove JDK14 from Jenkins completely: https://github.com/ev3dev-lang-java/openjdk-ev3/pull/75

**Comment by jabrena** [comment]
Fixed
