### ISSUE TITLE
Add support for OpenJDK 16 on AdoptOpenJDK

### ISSUE THREAD

**Issue by jacobcxdev** [ev3dev-lang-java/ev3dev-lang-java#798]
At the time of writing, OpenJDK version 16 reached [General Availability](https://openjdk.java.net/projects/jdk8/milestones#General_Availability) one month ago while the latest working version of OpenJDK on AdoptOpenJDK is version 15.

Would it be possible to add support for OpenJDK 16 to the ev3dev-lang-java project?

**Comment by jabrena** [comment]
I will need help for it

**Comment by jabrena** [comment]
No feedback
