### ISSUE TITLE
"Network is unreachable: connect" when running "testConnection" in the template project

### ISSUE THREAD

**Issue by MaiTheLord** [ev3dev-lang-java/ev3dev-lang-java#815]
Title is self explanatory. I put the brick's IP in `config.gradle`, and I am getting
 ```
> com.jcraft.jsch.JSchException: java.net.SocketException: Network is unreachable: connect
``` 
when running `testConnection`.

**Comment by jabrena** [comment]
Review the configuration, other users had the same issue but it is working fine.
