### ISSUE TITLE
Apply Factory Design pattern for Battery.

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#87]
Following the idea from @dlech to refactor Battery class to apply Factory Design Pattern.

_I don't think this is a good idea for the battery class. In the future, there could be more than one battery. For example, some sensor multiplexers and motor controllers have their own battery that provides information back to the EV3. Instead, it would be better to add a factory method to get the "System" battery - the battery whose "scope" attribute (POWER_SUPPLY_PROP_SCOPE property) returns "System". Other batteries will have scope of "Device" or "Unknown"._

**Comment by jabrena** [comment]
Related issue: https://github.com/jabrena/ev3dev-lang-java/issues/86

**Comment by jabrena** [comment]
@dlech I have implemented the factory. 
Do you know some device in the market which you can manage the battery?
Are you thinking in this Power Option?
http://www.mindsensors.com/rpi/41-uninterruptible-power-supply-for-raspberry-pi

**Comment by jabrena** [comment]
Take a look the example:

https://github.com/jabrena/ev3dev-lang-java/blob/master/library/src/test/java/ev3dev/java/examples/BatteryDemo.java

**Comment by jabrena** [comment]
Try to improve the method handling no input parameter:

**Idea:**
http://stackoverflow.com/questions/2330942/java-variable-number-or-arguments-for-a-method

**Comment by dlech** [comment]
> Do you know some device in the market which you can manage the battery?

I did not know of any specifically for robotics, but the example that you gave is a good one. We don't have a driver for it currently, but it would be easy to write one.

**Comment by jabrena** [comment]
Yes, it was interesting.

I am going to research this Device for v0.3.0
http://www.mindsensors.com/rpi/41-uninterruptible-power-supply-for-raspberry-pi

Anyway, this way will be consolidated for v0.3.0 not v0.2.0. 

This next week, I will close the number of features for v0.2.0 and I will begin with v0.3.0. Besides, I will use a Git branch to not work in master. (Bad habit, I recognize :( )

Many thanks

**Comment by jabrena** [comment]
REJECTED BY LEAN
